### ISSUE TITLE
CRLF end of line

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#247]
http://presscustomizr.com/support-forums/topic/release-1-1-13-code-mixes-unixdos-line-end/#post-92740

I tested this git repo and I got no results when trying to list the files with CRLF as end of line, while testing the customizr-pro/customizr builds (customizr from wp.org) I can see that basically almost all not automatically generated files have CRLF as end of line.
This is weird, maybe some grunt tool used when building the package adds them?

**Comment by Nikeo** [comment]
can we close this one ?

**Comment by eri-trabiccolo** [comment]
If you don't care about it yes, otherwise the issue is still there :) 
I think it happens when zipping the file.
Do you zip it with grunt?

**Comment by Nikeo** [comment]
yes I zip with grunt. not sure if there's a setting about that in the zip task...

**Comment by eri-trabiccolo** [comment]
well yeah there should be a way.
For what I see though, it shouldn't add them if not specified:
http://info.eps.surrey.ac.uk/FAQ/zip.html
see option -l and -ll
but that's for unix s.o. not sure how to do it in windows.

**Comment by eri-trabiccolo** [comment]
Ok I generated a build (zip and dir) with grunt on my linux machine and using this:
`find . -type f -exec file "{}" ";" | grep CRLF`
in order to find files with CRLF I had no results.

Using the same command in unzipped packages coming from wp-org ( or presscustomizr for which regards to customizr-pro) I had a lot of results.

So probably there's something wrong when creating the builds on (your) windows with grunt?
