### ISSUE TITLE
Add simple search in the menu

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#254]
- this option will appear in customizer > header > navigation
- inspiration for a simple field  http://jmbwebdesign.com/ OR http://themehorse.com/preview/interface OR http://tympanus.net/Tutorials/ExpandingSearchBar/ OR http://themes.themegoods2.com/nebula/business/
  http://tutsplus.github.io/css-experiments-with-form-field-animation/

=> search fields inspiration for pro users : 
http://tympanus.net/Development/MorphingSearch/
http://wpengine.com/ (in the menu)

**Comment by giorgioriccardi** [comment]
I know there are thousands of search box options and effects, but since you listed a very nice collection I thought to add this one, since I'm also contributing to this ;-)
http://mor10.com/

**Comment by Nikeo** [comment]
@giorgioriccardi looks good too thanks !
