### ISSUE TITLE
Header : add an option to wrap it in a container (no full-width)

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#255]

**Comment by eri-trabiccolo** [comment]
https://github.com/Nikeo/customizr/pull/61
I can re-do this for the current dev

**Comment by Nikeo** [comment]
yep

**Comment by eri-trabiccolo** [comment]
Ah, it might require some specs:
like: do we want the header borders applied to the "container" header's elements wrapper or to the header tag (which remains in full-width)? stuff like that
