### ISSUE TITLE
New Global Option : add a container width control, default is 1170px

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#256]

**Comment by eri-trabiccolo** [comment]
This means that by default we have to change our "row" in "row-fluid", otherwise a span12 in a container is still fixed whatever the container width is.

**Comment by Nikeo** [comment]
yes among other things. need to be studied with a detailed specs.

**Comment by eri-trabiccolo** [comment]
Well yeah, there are sensible elements, slider-boxed and grid-full image sizes depend on that value.
Also round-divs might suffer about that.
