### ISSUE TITLE
RTL : In the admin customize panel, when I hit any of the menu items the menu disappear 

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#260]
![wmn5rp-pjmjdlsvh09qs0y8wbybne06ccmm9f0pv7tk](https://cloud.githubusercontent.com/assets/3038156/9514835/935be56e-4c9d-11e5-938b-a1e106d3c09e.png)

Hi @JTS-IL, did you observe this problem too?

**Comment by JTS-IL** [comment]
Hi Nikeo
Yes, it happens on Hebrew WP, the main problem is the "Hi this is Nicolas..."
I have an English admin so I noticed it only yesterday.
Working on a fix. :-)

יעקב

**Sent from my mobile**
www.glezer.co.il

On 27 באוג׳ 2015, at 10:26, Nicolas Guillaume <notifications@github.com> wrote:



Hi @JTS-IL, did you observe this problem too?

**Comment by Nikeo** [comment]
ok. Great ! looking froward to it then :)
enjoy your day

**Comment by JTS-IL** [comment]
here's the fix

.in-sub-panel #tc-donate-customizer, .in-sub-panel .tc-cta-wrap {
    right: -450px;
}

**Comment by JTS-IL** [comment]
Hi @Nikeo ,
I need some help fixing this.
In "theme-customizr-control.css" there are some elements declared with .rtl prefix, so i tried to add the same prefix to  .in-sub-panel #tc-donate-customizer, .in-sub-panel .tc-cta-wrap
but It didn't do the job so I started to search for the code that is using the .rtl styles and couldn't find it.
Can you point me to the right solution?

**Comment by Nikeo** [comment]
Thanks Yaacov I'll merge this as soon as I can.
Nicolas

**Comment by JTS-IL** [comment]
I'm at my computer, but there is a complete solution in dedicated PR

יעקב

**Sent from my mobile**
www.glezer.co.il

On 3 בספט׳ 2015, at 17:08, Nicolas Guillaume <notifications@github.com> wrote:

Thanks Yaacov I'll merge this as soon as I can.
Nicolas

**Comment by JTS-IL** [comment]
Here is the PR: #273
