### ISSUE TITLE
RTL : The site header image jumped above the main menu

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#262]
![niq9laotzmxnziyiynrte-r8pymh1df7oay88kmyesi](https://cloud.githubusercontent.com/assets/3038156/9514889/e8188e18-4c9d-11e5-85cf-58f38974afbe.png)

**Comment by JTS-IL** [comment]
?
Looked at his site, it looks great.
Did he fix something?

**Comment by Nikeo** [comment]
he downgraded to 3.4.28 because he had a serie of issues related to RTL, this one and also #260 and #261

**Comment by JTS-IL** [comment]
OK!
digging...

**Comment by JTS-IL** [comment]
The issue is in mixins.less
I'm having some problems with github, so here is the fix:
old code:
***********************
    .row-fluid {
      width: 100%;
      .clearfix();
      [class*="span"] {
        .input-block-level();
        float: @floatDirection;
        & when (@is_rtl = false) {
        margin-left: @fluidGridGutterWidth;
        *margin-left: @fluidGridGutterWidth - (.5 / @gridRowWidth * 100 * 1%);
        }
        & when (@is_rtl= true) {
        margin-right: @fluidGridGutterWidth;
        *margin-right: @fluidGridGutterWidth - (.5 / @gridRowWidth * 100 * 1%);	
        }
      }
      [class*="span"]:first-child {
        & when (@is_rtl = false) {
        margin-left: 0;
        }
        & when (@is_rtl = true) {
        margin-right: 0;
        }
      }
***********************
new code
***********************
    .row-fluid {
      width: 100%;
      .clearfix();
      [class*="span"] {
        .input-block-level();
        float: @floatDirection;
        & when (@is_rtl = false) {
        margin-left: @fluidGridGutterWidth;
        *margin-left: @fluidGridGutterWidth - (.5 / @gridRowWidth * 100 * 1%);
       margin-right: 0;
        }
        & when (@is_rtl= true) {
        margin-right: @fluidGridGutterWidth;
        *margin-right: @fluidGridGutterWidth - (.5 / @gridRowWidth * 100 * 1%);
        margin-left: 0;	
        }
      }
      [class*="span"]:first-child {
        margin-left: 0;
        margin-right: 0;
        }
      }
***********************
that should fix #261 and #262

**Comment by eri-trabiccolo** [comment]
Hello JTS,
though it works, I'm not totally sure this is the dual of the ltr rule.
Would you like to test this PR -> #263
Do you think it could be at least a good starting point?

**Comment by JTS-IL** [comment]
As I remember - the left/right margin is not always a match for the flow direction.
that's why I used the "when" rules selectively.

**Comment by eri-trabiccolo** [comment]
You're right overall, but for which concerns to the grid system I think the margin-left is pretty tied to the float direction.
Anyway whatever would be the solution still there is something to do. For example why the logo right/left option doesn't work?. In rtl this rule should become "pull-left" .
https://github.com/Nikeo/customizr/blob/master/inc/assets/less/bootstrap/grid.less#L19

[class*="span"].pull-left,
.row-fluid [class*="span"].pull-left {
float: left;
}

**Comment by JTS-IL** [comment]
When I just started RTL-ing the theme, I did convert all the lefts to rights and vice-versa, but the result was not good

**Comment by JTS-IL** [comment]
About the logo - I think I didn't get RTL-ing this option yet :-(
