### ISSUE TITLE
Shall we add those HTML5 supports ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#270]
add_theme_support( 'html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
    ) );

See Twenty Sixteen
https://github.com/WordPress/twentysixteen/blob/master/functions.php#L81

**Comment by eri-trabiccolo** [comment]
Not sure about the gallery,
it might need CSS changes, IIRC
I have to check.

**Comment by ghost** [comment]
still don't know what that really does. 
using modernizr as we do should do most of the job.
