### ISSUE TITLE
What does $GLOBALS['content_width'] stand for ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#271]
https://github.com/WordPress/twentysixteen/blob/master/functions.php#L114

**Comment by eri-trabiccolo** [comment]
For what I can see in the wp code the most relevant code which uses that global variable is
in wp-includes/media.php
It uses that value to dinamically determine the size of medias like videos (embedded) and other media-like elements when building the playlist shortcode output.
We can set it with the px value of our content width. But our content width is a bootstrap column and it's filterable so we should have an associative array spanX => value.
Anyway I'm not sure how this global variable can be so significant considering the responsiveness.
Mah.
