### ISSUE TITLE
Post thumbnails not showing in post lists for imported posts

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#275]
Our thumb_fld isn't generated when the posts are imported (using or not the import/export wp procedure or just importing the sql db) and this is normal. Though when a post has a thumbnail we should create this field on the fly.
Actually I tried this:
1) remove the thumb_fld postmeta associated to a post from the db
2) as normal user (not logged in) reload the post list
Result:
thumb_fld created in the db and thumbnail shown.
What do you think can the issue be?
The only thing I can think of is an empty $_thumb_id

p.s.
do we use all this method in order to show attachments as featured image? right? 
So to avoid always cycle among them. right? :D

**Comment by eri-trabiccolo** [comment]
I also ran an export/import but wasn't able to reproduce the issue :/

**Comment by eri-trabiccolo** [comment]
What do you think if we put a call to action button in the post list customize section to re-generate the thumb field (this button should have a description which doesn't make users think we re-generate the thumbnails ). The code could be something simple like the following (the LIMIT is to avoid memory isseus):
```php
function generate_tc_thumb_fld(){
  global $wpdb;
  $_has_posts = true;
  $_offset = 0;

  while ( $_has_posts ) {
    $_posts = $wpdb->get_results( "
      SELECT `ID` FROM $wpdb->posts 
      WHERE `post_status` = 'publish'  
      LIMIT 20 OFFSET " . $_offset
    );
    $_has_posts = count($_posts) > 0;
    if ( $_has_posts ) {
      $_offset = $_offset + count($_posts);
      if ( ! class_exists( 'TC_post_thumbnails' ) )
        TC___::$instance -> tc__( array('content' => array( array('inc/parts', 'post_thumbnails') ) ), true );
      foreach ( $_posts as $_post) 
        TC_post_thumbnails::$instance -> tc_set_thumb_info( $_post -> ID );
    }
  }
}
```

But I'm assuming the issue is related to something which prevents the automatic refresh which your code already properly provides.

**Comment by eri-trabiccolo** [comment]
FYI the user having the issue solved it after this suggestion:
1) disable your plugins (maybe one of them might have conflicted)
2) browse the whole blog (post-lists) as admin

point 2 because we always refresh the thumb fld when user can upload images (right?).
I'm not sure if the user followed the 1) step too or if it was needed.

**Comment by Nikeo** [comment]
After all this is an edge case.
instead of adding a new button to the customizer, wouldn't it possible to hook at the end of the import process (there must a be a hook there) and run your code ?

**Comment by eri-trabiccolo** [comment]
A better version of it, yes, makes sense.
Anyway I tried to reproduce it but I couldn't reproduce it.
Hopefully will not be so much expensive.
