### ISSUE TITLE
Grid expanded post

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#277]
At the moment the expanded sticky post is not the latest published but just the first in the array of the sticky_posts option. We should retrieve the latest published among those posts.A custom SQL should be the less expensive way.

**Comment by Nikeo** [comment]
oh ok!

**Comment by eri-trabiccolo** [comment]
Can you further test this?
I discovered that doing the post slider.
I was sure the sticky_posts option was well ordered.
When doing the grid I've been mislead by:
https://codex.wordpress.org/Sticky_Posts#Display_Sticky_Posts

that "the first" ... :(

**Comment by Nikeo** [comment]
I'll do so (tomorrow morning if I can)

**Comment by eri-trabiccolo** [comment]
Just tested that that option is "updated" incrementally, so not ordered by publication date, say ordered by "date of setting them sticky"
(at least here, and with my shiny shape :/)

**Comment by Nikeo** [comment]
ah ok.
Let's put it this way, if reordering the sticky posts by their actual plublication date is too much of coding, we can stick to the default WP behaviour (ordered by date of sticky status set).

**Comment by eri-trabiccolo** [comment]
I think we can do that with small effort (and resources). Just with an SQL to query wp_posts where ID in ({array of sticky posts}) order by post_date , then extract the first result.
If you're fine with this we can do that.

about:
> we can stick to the default WP behaviour (ordered by date of sticky status set)

Sure, nobody complained about that, but consider that this isn't the normal blog behavior. In the normal blog (you can see it with the alternate layout) the sticky posts are in head and ordered by pub date.
