### ISSUE TITLE
The notices keep popping out

### ISSUE THREAD

**Issue by Oreolek** [presscustomizr/customizr#279]
Here's the thing. The notices are broken.

"The footer has no widgets" notice keeps showing each time when the footer has no widgets. The only way to disable it is to add some widget which is not always desired.

"You can now display your menu as a vertical and mobile friendly side menu, animated when revealed." keeps popping out for everyone, **even for non-admins** - everytime the vertical side menu is disabled. If you disable the horizontal menu, however, another notice pops up. The only way to disable them off is to turn both menus on.

Wordpress 4.3, if that's relevant.

**Comment by Nikeo** [comment]
OK thanks for reporting this @Oreolek

**Comment by eri-trabiccolo** [comment]
Hello Oreolek
what about disabling the notices in Appearance -> Advanced options -> Front-end placeholders and help blocks.
does that work?

**Comment by Nikeo** [comment]
Hi Rocco, I understand that you've not been able to reproduce this issue, am i right ?

**Comment by eri-trabiccolo** [comment]
Right, unable to reproduce it.
