### ISSUE TITLE
Pages in search results

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#280]
Since some wp versions ago (don't know exactly when) the pages are included in the search results.
Do we want to allow this?
Also consider that our code to include cpt in archives and search results excludes pages (as the original search results did as well)

**Comment by Nikeo** [comment]
I think we could include the pages now...I didn't notice this. But I don't see any reason why they should be excluded from the default search engine.

**Comment by eri-trabiccolo** [comment]
Well yeah they're included, we just exclude them when including cpt.
Anyway some wp version ago pages were excluded, or am I wrong?
Anyway now when including cpt in archives and search results we should:
1) include pages in search results, so exclude just attachments among the built in types.
2) exclude pages in archives (date archives)
so what we can do is using the same code for archives but when is_search add also pages as we do with posts, I think it's fine.

**Comment by Nikeo** [comment]
I don't have all this code exacly in mind, but yeah sounds good

**Comment by eri-trabiccolo** [comment]
https://github.com/Nikeo/customizr/blob/master/inc/parts/class-content-post_list.php#L338

It should be a matter of adding at line 352
`if ( is_search() ) $post_types['page'] = 'page';` 
(something of the sort)
Have to test this.
