### ISSUE TITLE
Display Version Number

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#282]
On Dashboard, WP displays Version 4.3. Is it possible to add a similar feature for Czr/CzrPro?

(May be my problem only as my CzrPro doesn't auto-update. Just discovered I had 1.2.2 on a site rather than 1.2.5)

**Comment by Nikeo** [comment]
Yes there's a filter for this in the core.

**Comment by Nikeo** [comment]
I close this for the moment since the version of the theme can always be checked from appearance > theme by cicking on the details link of any themes
