### ISSUE TITLE
Grid expanded post edit link not reachable

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#286]
The edit link in the grid expanded post must be placed outside the summary div so to not be overlapped by the link to the post, as we already do in GC.

**Comment by Nikeo** [comment]
Did we fix this ? :)

**Comment by eri-trabiccolo** [comment]
Nope :)
we talked about fixing all the grid related things after the new framework. But it was about to be finished then .. :D 
We probably should fix it anyways.
Do you want it? Can take care about it soon if you want.

**Comment by Nikeo** [comment]
ok let's fix it when you can

**Comment by eri-trabiccolo** [comment]
Ok
