### ISSUE TITLE
in Advanced options, add a text field to add scripts / style sheets

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#304]
* Can be used to embed any type of script like Google Analytics, stylesheets
* Could be contxtualized in the future
![script_field](https://cloud.githubusercontent.com/assets/3038156/9986986/00336f46-6043-11e5-8b3f-bd705d72d4b9.png)

**Comment by eri-trabiccolo** [comment]
Do you think is possible?
Where can we store the scripts?
We cannot even store a real CSS (quotes and double quotes not allowed anymore)?
Will wp.org themes rules allow the storing in the only one option we can use? (don't think so)
I think we can just provide a field for google-analytics id (UA-xxxxx) and have the code embedded in the theme.
What do you think?

**Comment by Nikeo** [comment]
Some plugins are doing it like this one : https://wordpress.org/plugins/simple-embed-code/screenshots/
This is not priority n° 1 but let's keep in it in a corner of our mind...:)

**Comment by eri-trabiccolo** [comment]
Well yeah, in each post we can.
Otherwise... addon...

**Comment by Nikeo** [comment]
not a priority.
