### ISSUE TITLE
Post lists: allow users to avoid the prepending of the sticky posts in the blog (meaning also the front page displaying recent posts)

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#307]

**Comment by Nikeo** [comment]
could you elaborate on what you had in mind ? :)

**Comment by eri-trabiccolo** [comment]
Eheh,
this is something put here after one of our conversation.
Basically .. set the "ignore_sticky_posts" wpquery var to true.

**Comment by Nikeo** [comment]
is it a request you've already seen from a user ?

**Comment by eri-trabiccolo** [comment]
Nope,
I remember we decided to add this option after the slider of posts. 'Cause you can use the slider of posts to show only the sticky posts and then you might want to not see them in the post list in home/blog.
That was the sense of the option ;)

**Comment by Nikeo** [comment]
mm ok yes rememeber now.
Not urgent and might bring some confusion for users who forgot they checked this option and wonder where are their sticky posts...
I close it for now.

**Comment by eri-trabiccolo** [comment]
:)
