### ISSUE TITLE
Link to external icon shall never be underlined

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#311]
when a selector has the text-decoration:underline css property, the external link icon looks ugly

**Comment by eri-trabiccolo** [comment]
What can we do in this sense?
In js when adding the span act also on the link and add an inline style or a CSS class (to define in our tc_common) where we override the text-decoration with "none" (maybe also !important) ?

**Comment by Nikeo** [comment]
The solution will consist to go from
```css
<span style="text-decoration: underline;">
  <a href="http://google.com" target="_blank">to the thing</a>
  <span class="tc-external"></span>
</span>
```

To
```css
<a href="http://google.com" target="_blank" style="text-decoration: underline;">to the thing</a>
<span class="tc-external"></span>
```

this has to be added in the jQuery plugin
* detect is the parent has this text-decoration property
* de-wrap it

**Comment by eri-trabiccolo** [comment]
Ah, this happens when you specifically underline a string in the editor.
Fine.

**Comment by Nikeo** [comment]
yes should have mentioned that actually !

**Comment by eri-trabiccolo** [comment]
Eheh don't worry.
It was me who was thinking about the underling decoration applied just to the link so actually couldn't see the ugliness too :P

**Comment by eri-trabiccolo** [comment]
Ok, probably we need a different approach.
What if the whole text is underlined? I mean a big text with a link inside.
Looks like that we cannot even wrap the ahref+external-span in an a span which reverts the underlining ...
The only thing we can do is to remove the external-icon top property so it's on the same line of the link and it will be a little less ugly.

**Comment by eri-trabiccolo** [comment]
Unless we want this other approach.
Close the underlined span before the link and re-open it after our icon, but this is very ugly stuff :D

**Comment by Nikeo** [comment]
no no I've been also thinking about something like this just now, but just awful.
you're right, my example was only a subcase and wasn't covering everything.
So, unfortunately the only reasonnable and not too expensive option is too disable the external link feature if a parent is underlined...
Design wins sometimes ... well all the time in fact :)

**Comment by Nikeo** [comment]
spec updated on aszzzssaaaanââââ

**Comment by eri-trabiccolo** [comment]
ahaha,
well there's still the option .. remove the top property from the icon-span.
doesn't convince you?

**Comment by Nikeo** [comment]
no because its too much of a tinkering stuff I think, and the uglyness could still be visible when line-height change, etc...

**Comment by eri-trabiccolo** [comment]
yes that's true. ok
