### ISSUE TITLE
Sticky header in mobiles while zooming

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#317]
When you zoom in mobiles (two fingers) often happens that you also "scroll" the window triggering the sticky header.
This can be pretty annoying specially for users who want to zoom on the logo image.
I'm not sure how much we can do to avoid this.
Most likely what we can do is to tie the triggerHeight to the zoom-level, so increase it by the zoom factor ( triggerHeight * zoom-factor ) - if there was a good cross-browser way to know the current zoom level, but anyway we can consider it as 1 as minimum, at least in mobiles.

p.s.
you can actually avoid that if you keep the upper finger fixed and move the other finger to the bottom when zooming in (vice versa when you zooming out), but we should avoid relying on the arthritis of the users :P

**Comment by Nikeo** [comment]
I ould replicate the issue but it's pretty minor to me. Once zoomed it's easy to scroll up to see the actual zoomed logo.
closed for now
