### ISSUE TITLE
In version 3.4.8, the breadcrumb will only works if the categories are in alphabetical order.

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#319]
An issue related to breadcrumb that I would like to raise here (same issue was raised in https://wordpress.org/support/topic/overriding-customizr-breadcrumb)

In version 3.4.8, the breadcrumb will only works if the categories are in alphabetical order.
Reported as a comment here http://presscustomizr.com/snippet/remove-breadcrumb-top-pages/

For example,
If a site has a page with title “Countries”
and categories are “Countries”, “Canada” and “USA”

Scenario 1
A new post is added, title = “New York”
category = “Countries” and “USA”
the breadcrumb will show as “Home >> Countries >> New York” instead of “Home >> Countries >> USA >> New York”

Scenario 2
A new post is added, title = “Ottawa”
category = “Countries” and “Canada”
the breadcrumb will show correctly as “Home >> Countries >> Canada >> Ottawa”

The solution (or workaround) is to name the categories like these:-
“Countries”
“1: Canada”
“2: USA”

then breadcrumb will show correctly for “USA”:-
“Home >> Countries >> 2: USA >> New York”

**Comment by eri-trabiccolo** [comment]
weirdest bug ever seen :D
