### ISSUE TITLE
Featured pages text trim

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#320]
reported here -> https://wordpress.org/support/topic/customizr-and-qtranslate-in-featured-pages?replies=6
Should be the same fixed in fpu, which I identified as:

> If you have a text >=200 chars with no spaces after the limit strpos returned false, and substr from 0 to false, returned nothing, then you had just "..." displayed.

Solution:
port fpu text-trim code for fp free too (similar to the text trim for the slider of posts, I propose to move the function in utils ).

**Comment by Nikeo** [comment]
I think you fixed that in a later PR Rocco right ?

**Comment by eri-trabiccolo** [comment]
Nope not fixed for standard fp.
We should use the same method used for fpu and for the slider of posts text trimming.
I can take a look at it ~now if you want. But it's about those things you won't have the time to review :P

**Comment by Nikeo** [comment]
ok take it I'll have time to review those kind of *relatively small* devs

**Comment by eri-trabiccolo** [comment]
Ok fine.
I might move the code in the utils class so the slider and fp will use the same code.
(I might change the fpu code too)

**Comment by eri-trabiccolo** [comment]
p.s.
this move was planned:
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-slider.php#L1448

**Comment by eri-trabiccolo** [comment]
Let's make this simple, I'll just change the fp code according to the tc_trim_text linked above.
With the new framework we'll do the whole move.

**Comment by Nikeo** [comment]
all right !

**Comment by eri-trabiccolo** [comment]
I need an answer to fine tune the fix, see the last PR comment.

**Comment by Nikeo** [comment]
Yep i can t before tomorrow unfortunately

**Comment by eri-trabiccolo** [comment]
Sure np ;)
