### ISSUE TITLE
Sticky footer sometimes fails when the golden ratio is applied

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#321]
When the golden ratio applies and the grid elements are shrinked the sticky footer doesn't detect any change (no window resize).

Solution:
In the centering imgs plugin trigger an event which the sticky-footer would listen to.

**Comment by Nikeo** [comment]
Why the resize is not detected in this case ? Did you find any possible reason ?

**Comment by eri-trabiccolo** [comment]
Because the "window" isn't resized.
an "inner" resize doesn't imply a "window" resize, hence no tc-resize triggered.
we should find a way to observe the actual content resize (like I think the smoothscroll does).
I read something about in the past, but solutions weren't that cross-browsers and may have problems when html,body height is set to 100% etc etc.
Will look more into this once real devs will end, trying to find a solution :D

**Comment by Nikeo** [comment]
ok, got it thanks
ready to merge
