### ISSUE TITLE
Problem with "dynamic sidebar reordering"

### ISSUE THREAD

**Issue by kemmettchris** [presscustomizr/customizr#324]
Left sidebar remains on top in mobile.  Have tried several CSS customization's with and without the (box) checked in the customizer for "dynamic sidebar reordering" under sidebar/responsive settings. My website is www.therealstrategy.com.

Videos also don't seem to be resizing in mobile.  I have tried several CSS tricks for that and have yet to succeed.  This may not be the right place for this, but I figured some more educated and familiar coders would be here. 

Thanks for any help.  

I looked over this: http://presscustomizr.com/snippet/media-queries-responsiveness/ 

Though none of the sizes seemed to make a difference.

**Comment by Nikeo** [comment]
Hi @kemmettchris, as you said it it's not the right place to report a problem happening on your website.
Please report it first on the user forum : https://wordpress.org/support/view/theme-reviews/customizr

If it is a reproductible bug, then we'll try to find a fix. Thanks :)
