### ISSUE TITLE
New social network : add Yelp and Xing. Icons ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#326]
- Need to check if the yelp and xing icons are included in the embedded theme icons : genericons and entypo

**Comment by eri-trabiccolo** [comment]
None of them are included in genericons and entypo :|

**Comment by eri-trabiccolo** [comment]
Do we want to switch to Font-Awesome icons set?
https://wordpress.org/support/topic/add-the-icons-of-social-networks-please?replies=4
That set is allowed as it's licensed under SIL.
https://make.wordpress.org/themes/handbook/guidelines/resources/#gpl-compatible-icon-sets

It has also the cited Xing and Yelp

**Comment by Nikeo** [comment]
yep looks like a good alternative

**Comment by eri-trabiccolo** [comment]
hueman uses fontawesome, right?

**Comment by Nikeo** [comment]
don't know have to check

**Comment by eri-trabiccolo** [comment]
yes it does:
https://github.com/presscustomizr/hueman/tree/master/fonts
for example:
https://github.com/presscustomizr/hueman/blob/master/style.css#L211
