### ISSUE TITLE
WP 3.7.4 Customize Preview: Does the live preview (transport:postMessage) correctly work?

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#327]
Need to investigate whether is a problem in the preview js or on how we change the setting value (with select2.val())

Actually here no options with transport postMessage are working with 3.7.4.
Probably an issue on my end then. Will look further more into it.

**Comment by Nikeo** [comment]
any updates on this ?

**Comment by eri-trabiccolo** [comment]
Nope Nico sorry.
I was looking for some tester :P 
Will look into it soon (today/tomorrow)

**Comment by eri-trabiccolo** [comment]
I confirm.
Doesn't work!
That's because 'preview-init' signal isn't triggered in older wp versions.
And it's fundamental for us..
https://github.com/presscustomizr/customizr/blob/master/inc/admin/js/theme-customizer-preview.js#L18

Alternatives?
```$(document).ready(fireCzrPrev);```

seems fine also for newer versions.
Otherwise we can fallback on it for old wp-versions but we need a "marker" for old versions.
So need to investigate when that event has been introduced (maybe 4.0?)
