### ISSUE TITLE
Blog cat picker : Sticky Posts should be displayed on top of the others  if they belong to a filtered blog category

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#331]
Sticky posts:
at the moment we filter the query using the var cat. This doesn't automatically ignore sticky posts, so I force this.
This because the wp sticky_posts treatment (put them in head) works this way:
- from the retrieved posts pick up the stickies and put them in head
- from the array of the sticky posts put in head those not already present (see step above)
[ignore_sticky_posts var prevents the routine above]
So in our case when we show the posts from a certain category, if we don't ignore the sticky posts we'll have all the posts of the selected categories with the stickies (also of excluded categories) in head.
What we can do is offer more options to people like:
- ignore sticky posts [this is our default]
- still display sticky posts (even if not from the selected categories)
- display sticky posts only of the selected categories (this might need some thinking anyway)

**Comment by eri-trabiccolo** [comment]
Ok, so here we have to decide which options to allow among these:
ignore sticky posts [this is our default]
still display sticky posts (even if not from the selected categories)
display sticky posts only of the selected categories (this might need some thinking anyway)

all three?
when decided this can be put in the "ignore sticky post" dev
