### ISSUE TITLE
Smartload and jetpacks's photon

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#334]
https://wordpress.org/support/topic/customizr-bug-with-photon-and-load-images-on-scroll?replies=2#post-7485641

Why:
our parser:
https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-utils.php#L98
their parser:
https://github.com/Automattic/jetpack/blob/master/class.photon.php#L55

So the solution is the one I proposed in the wp-org reply.
Also we already use this approach for nggalleries -> https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-plugins_compat.php#L395

Hence I propose to set by default the priority of that hook to PHP_INT_MAX (and remove the nggallery plugins compat code

>Should anyone here present know of any reason that this couple should not be joined in holy >matrimony, speak now or forever hold your peace.

p.s.
maybe this is an enhancement more than a bug, 'cause technically there's no error :)

**Comment by Nikeo** [comment]
I'll hold their peace.

yes enhancement more than bug I agree
thanks ;)

**Comment by eri-trabiccolo** [comment]
:)
