### ISSUE TITLE
Bleeding 1px lines on iPad/Safari FPs

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#338]
https://wordpress.org/support/topic/images-featured-pages-show-incorrect-on-ipadsafari

Can reproduce this on iPad. Unable to diagnose with Developer Tools.

**Comment by eri-trabiccolo** [comment]
So basically this is an FPU issue and most likely just with some specific browsers (safari) on specific mobiles (iPad - iPhone).
Would love to reproduce it, have to find an iPad somewhere :D

**Comment by ghost** [comment]
fixed in latest version of FP
