### ISSUE TITLE
Select a submenu expansion option disappears

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#340]
Hi,

With reference to this support thread https://secure.helpscout.net/conversation/127427471/1162/

The option Appearance -> Customize -> Header -> Navigation Menus -> Select a submenu expansion option disappears after saving. 

Re-appears only when switching from Side Menu to Horizontal (Switch back and forth a few times) in Appearance -> Customize -> Header -> Navigation Menu -> Select a design : side menu (vertical) or regular (horizontal).

Hope you understand my explanation.

Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Perfectly, Denzel.
I can reproduce the issue, will look into it.
Thanks.

Rocco

**Comment by denzelchia** [comment]
Hi Rocco,

Nice to meet you!
Thank you for confirming this bug.

By the way, the codes you wrote are superb! 
I cannot understand most of them and is glad to be able to look at your work and learn from you.

Have a nice weekend!

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Nice to meet you too Denzel, and thank you for your appreciation!
Sometimes I'm unable to understand what I wrote too :D.
It is a continuous learning in this field.. or copying :D
Thanks and have a nice weekend you too!

Rocco

**Comment by Nikeo** [comment]
@denzelchia thanks for reporting this
@eri-trabiccolo thanks for the PR. ready to merge in dev.
Team work at its best !

**Comment by eri-trabiccolo** [comment]
:D

**Comment by denzelchia** [comment]
Thanks!
