### ISSUE TITLE
The grid doesn't take care of the custom max-height in a left-sidebar layout

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#345]
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-post_list_grid.php#L783
As you can see the 'l' "column" has still a fixed height.

**Comment by Nikeo** [comment]
Just to refresh my memory, can you explain how to replicate this problem ?
Why only left-sidebar ?

**Comment by eri-trabiccolo** [comment]
'Cause you designed that way, I don't know why :P 
That line, for my understanding, says:
>'2' => array( 225 , 225, $_h, $_h ),

when the grid layout is formed by 2 columns use the following heighs:
2 sidebars = 225
1 sidebar - left = 225
1 sidebar - right = custom_height
no sidebars = custom_height

How to replicate? Change the grid thumb height value.
Then switch from a right sidebar layout to a left sidebar layout and see the difference. :D

**Comment by eri-trabiccolo** [comment]
Or that should be.. looks like I cannot reproduce it?

**Comment by eri-trabiccolo** [comment]
Ah yeah, I was using a smaller thumb height, but in that case all the values will be lowered to the custom height.
So to reproduce it you should use a custom height > 225

**Comment by Nikeo** [comment]
ok got it. yes it's a mistake. good catch :)

**Comment by eri-trabiccolo** [comment]
I honestly dunno why I didn't push a PR before.
Sorry :)
