### ISSUE TITLE
Customizer front page options shall be in the same default order as they're display on front

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#346]
Should be 
- Slider Options
- Featured Pages Options
- Choose content and layout

**Comment by eri-trabiccolo** [comment]
I can do this in the slider PR since I'm hooking to the front_page settings using priorities.
Are you fine with this?

**Comment by Nikeo** [comment]
I would prefer a separate PR about this issue

**Comment by eri-trabiccolo** [comment]
Fine.
