### ISSUE TITLE
conflict with VisualComposer with tab's 

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#354]
https://wordpress.org/support/topic/customizr-infinite-scrolling?replies=1

Greetings,

I have WP 4.3.1, Customizr 3.4.11 and the newest VisualComposer.
In WP I have create with VC a tabbed content.
Unfortenly, the tabs are not working.
I have open a ticket by VirtualComposer and she say, with a default theme (Twenty Fifteen) it works.
I have change to Twenty Fifteen and it works realy.
The support from VC write, that here is a conflict with javaScript from custimizr.

Can everybody help me?
Thank's
Michael

**Comment by eri-trabiccolo** [comment]
wrong post link,
the one above is about infinite scroll :P

**Comment by Nikeo** [comment]
oops fixed. Thanks :)

**Comment by eri-trabiccolo** [comment]
Ok,
vc has a lot of "anchors", 'cause it allows
- horiz tabs
- vert tabs
- accordions
- sliders
and so on..
Now we can do 2 things:
1) skip all the links children of ".vc_row"s (which is basically the class for all the parents 
2) try every possible, known, elements which can use the anchors and exclude them one by one.

What's your opinion?
I'm for the 1) :D

**Comment by Nikeo** [comment]
yep I'll go for the 1) two !

I like this choice/alternatives your giving in your latest PR :)

**Comment by eri-trabiccolo** [comment]
eheh.
We really don't have a way to contextualize the pages using vc (or at least I'm not aware about that, I should dig in the code - couldn't find it easily atm), so we have to add this new excluded parent when vc is enabled.
