### ISSUE TITLE
Do we really need to load tc_wp_filters so early? ( on after_setup_theme)

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#358]
=> problem to solve : disabling the smartload for a specific context when setting up a view on 'wp'
It's easy to disable the tc_img_smart_load option with : 
```php
add_filter( 'tc_opt_tc_img_smart_load', '__return_false' );
```

BUT : the images will still be parsed since this has been set very early by 

```php
/**
      * hook : after_setup_theme
      * @package Customizr
      * @since Customizr 3.3.0
      */
      function tc_wp_filters() {
        add_filter( 'the_content'                         , array( $this , 'tc_fancybox_content_filter' ) );
        if ( esc_attr( TC_utils::$inst->tc_opt( 'tc_img_smart_load' ) ) ) {
          add_filter( 'the_content'                       , array( $this , 'tc_parse_imgs' ), 20 );
          add_filter( 'tc_thumb_html'                     , array( $this , 'tc_parse_imgs' ) );
        }
        add_filter( 'wp_title'                            , array( $this , 'tc_wp_title' ), 10, 2 );
      }
```

The only solution right now is to remove the parse filters, which is a pain.

Is there a reason justifying hooking tc_wp_filters so early ?
A more convenient way would be to fire this callback after 'wp'.
'wp_head' would be a good candidate.

@eri-trabiccolo any opinion ?
Thanks !

**Comment by eri-trabiccolo** [comment]
I'm with you:
For example I had to unhook the parse_imgs on the thumbs for the posts slider:
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-slider.php#L413
In that case wasn't a pain :D but I agree.
Also.. I think we need a way to singularly exclude imgs (singularly avoid the parsing), like data-no-retina, something like data-no-tcsmartload (we already exclude imgs whic already have a data-src set). Think about if we want to put a slider in the content with a shortcode in the future.
(same for fancybox).

Back to your question :D
So with `wp_head` also after `template_redirect`, I think is a good choice.

I tend to agree and don't see a problem here.
I also think it's something which we just inherited from old versions, where all the "setup" was in the same callback on `after_setup_theme` then you split it to have a better order. :) (not sure, but is more likely :D)

**Comment by Nikeo** [comment]
yes it probably come from here.

thanks, I wanted to make sure that you did not have in mind some possible regression if hooked later.

easy to fix then, not urgent. I add it in ASJSJSJANNNNâaa :)

**Comment by eri-trabiccolo** [comment]
ahhaha :D 
Nope cannot see a real problem (we also removed this 
https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-plugins_compat.php#L385
from dev so I don't think there are other points where we do that before wp_head)
Maybe the only problem will be with the resources, 'cause wp_enqueue_scripts is before wp_head.
But actually we there don't use that filter, we just directly use the "filterable" option:
https://github.com/presscustomizr/customizr/blob/dev/inc/class-fire-resources.php#L215

So there might be this inconsistency (actually there's potentially already :D)
