### ISSUE TITLE
Edit posts / pages / slider / featured pages buttons shouldn't be displayed in customizing context

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#361]
will have to be fixed in the new framework

**Comment by eri-trabiccolo** [comment]
Yep I always wanted to ask you that.
What about the help blocks? While the blocks have sense as "reminder" in customize too, their links will not work.
Anyway about the edit buttons, do you think is good adding php logic to not display them while we can just "hide" them with:
`.is-customizing .edit-link {
    display: none;
}`
?

**Comment by Nikeo** [comment]
yes it will also apply to help blocks good point

**Comment by Nikeo** [comment]
yes I would rather treat this server side.
It's always better to save even one line of CSS...:)

**Comment by Nikeo** [comment]
stylesheets are already heavy !

**Comment by eri-trabiccolo** [comment]
help-block and edit-button php classes :P 
Especially for the help-block is something I thought we needed when doing the post/page help block.
We can uniform the block in a base class (also the js) and for those blocks which are much different we can either extend this class or even pass to the constructor a callback when instantiating it.

**Comment by eri-trabiccolo** [comment]
I though about doing this with CSS (as I proposed in the chat), and I thought that would be better to prevent the displaying in php as to avoid any kind of conflict with any plugin which might use the same CSS class for their purposes.
