### ISSUE TITLE
Add an option to disable the logo link to home page

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#366]
a checkbox in Global settings > logo

**Comment by eri-trabiccolo** [comment]
Valid just for the logo or also for the title?

**Comment by Nikeo** [comment]
actually for both.
In this case, this setting should be located in Header > Design and Layout

**Comment by eri-trabiccolo** [comment]
Fine,
so the "a" tags, if you agree, will become "span" tags

**Comment by Nikeo** [comment]
yes! 100% agree. (should keep the class though)

**Comment by eri-trabiccolo** [comment]
sure :)
