### ISSUE TITLE
Header menu notice : update the documentation link

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#367]
this is a dead link : http://docs.presscustomizr.com/customizr/header-options/#navigation
Are there other like this ?

**Comment by eri-trabiccolo** [comment]
from a rapid search ( W grep :) ), at least:

https://github.com/presscustomizr/customizr/blob/dev/inc/class-fire-utils_settings_map.php#L1021
https://github.com/presscustomizr/customizr/blob/dev/inc/class-fire-utils_settings_map.php#L1145

slider:
https://github.com/presscustomizr/customizr/blob/dev/inc/parts/class-content-slider.php#L1020
https://github.com/presscustomizr/customizr/blob/dev/inc/parts/class-content-slider.php#L1026
https://github.com/presscustomizr/customizr/blob/dev/inc/admin/class-tc-controls-settings.php#L144

https://github.com/presscustomizr/customizr/blob/dev/inc/parts/class-content-sidebar.php#L149

https://github.com/presscustomizr/customizr/blob/dev/inc/admin/class-fire-admin_page.php#L63

**Comment by Nikeo** [comment]
oh yes !
Not cool

**Comment by giorgioriccardi** [comment]
from dashboard this helps to check ;-)
https://wordpress.org/plugins/broken-link-checker/

**Comment by Nikeo** [comment]
should have run this one before the latest release :(
thanks

**Comment by eri-trabiccolo** [comment]
before many releases ago :)

**Comment by giorgioriccardi** [comment]
a client of mine had over 500 broken links, mostly from media galley, Google did not say a single word on that mess... and on the same line:
FYI every once in a while I run this: https://wordpress.org/plugins/disk-usage-sunburst/
It helps detecting plugins storing stuff and other junk that piles up in Terabytes

**Comment by eri-trabiccolo** [comment]
Thanks for the tips Giorgio :).
Just ran broken link checker, looks like it doesn't help for this particular issue, it didn't find them.  Or maybe I don't know how to use it :D

**Comment by giorgioriccardi** [comment]
did u set it properly here:
..../wp-admin/options-general.php?page=link-checker-settings 
?
last option would be the nuclear check:
http://awesomescreenshot.com/0ef5c6cn8d

**Comment by eri-trabiccolo** [comment]
mm no, I'm not sure I set it properly :) I don't know whether it really looks for what we need.
Did you test it? Does it find Customizr theme broken links?

**Comment by giorgioriccardi** [comment]
Nope, is not finding Customizr theme broken links... I'll see if it can be tweaked a bit.

Keep u posted

**Comment by eri-trabiccolo** [comment]
I changed those in the slider class, though I think we need anchors in the doc.
For example we should point to the "Front page slider" heading.

**Comment by Nikeo** [comment]
yes I agree anchor would be better but let's do whitout them for now

**Comment by eri-trabiccolo** [comment]
So pointing to the Front Page doc for now:
http://docs.presscustomizr.com/article/102-customizr-theme-options-front-page

**Comment by Nikeo** [comment]
Hi Rocco,
Did we ( you) fix all those dead links in a PR afterwards ? I guess so but please confirm :)

**Comment by eri-trabiccolo** [comment]
Not all 'cause it involved several files and I wanted to avoid conflicts.
If you want I can do this right now...

**Comment by Nikeo** [comment]
ok go ahead. We'll make a voice chat tomorrow about all those 'small' fixes before you come to Nice. The idea is to clean up this issues list  a little bit :)

**Comment by eri-trabiccolo** [comment]
Ok
(I'll not be available tomorrow morning :/)

**Comment by eri-trabiccolo** [comment]
I think I have to add the anchors in the docs, 
I'll do that for the important links.

**Comment by eri-trabiccolo** [comment]
Should be fixed now.
Hopefully I haven't missed any other broke link..
