### ISSUE TITLE
Menu Icon Position

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#368]
Hi,

I believe this is a CSS bug, or probably caused by the loading sequence of elements into header.

If Display the tagline is checked and Social links in header is unchecked, the menu icon goes to the center.

This is screenshot of my Header Design and Layout setting.
http://i.imgur.com/VtXFOjd.jpg

This screenshot of my Navigation Menus setting.
http://i.imgur.com/fOAYemI.jpg

This is screenshot on front end.
http://i.imgur.com/BJrXqne.jpg

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks for this Denzel.
Yes this is another "known {$something}" :D Not sure though if @nikeo wants to do anything for that. The thing is that if we put it below the tagline, then a big empty space will result, and I can already hear complains :D 
On the other hand, "fixing" it should be simple by adding the property clear: right; (or both) to the .tc-header .btn-toggle-nav 
so probably we can write it somewhere in the docs.
We'll see ;)

**Comment by denzelchia** [comment]
Hi Rocco,

Ok, I understand. Thank you! :)
