### ISSUE TITLE
WPGlobus plugin compatibility

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#372]
* Bug with https://fr.wordpress.org/plugins/wpglobus/
* Reported in the forum : https://wordpress.org/support/topic/wpglobus-and-customizr?replies=2#post-
7601863

Hi there, since installing the WPGlobus plug-in I have the flolowing warning message appear in the header-area of my customizr theme:

'Warning: array_filter() expects parameter 1 to be array, string given in /home/users/fotrvftp/fotopooier.nl/wp-content/themes/customizr/inc/parts/class-header-nav_walker.php on line 81'

**Comment by eri-trabiccolo** [comment]
Another lang plugin? :| 
Fix ready.

**Comment by Nikeo** [comment]
already?

**Comment by eri-trabiccolo** [comment]
well, yes the error was clear, and I could reproduce it.
