### ISSUE TITLE
Plugin Conflict : SiteOrigin Page Builder + Ultimate Addons for SiteOrigin plugin

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#386]
Using the SiteOrigin Page Builder plugin, when Users use the Ultimate Addons for SiteOrigin plugin add-on it conflicts with CSS (symptom is it displaces the 3rd Featured Page.

https://wordpress.org/support/topic/featured-pages-are-misplaced-please-how-do-i-fix-it

https://wordpress.org/support/topic/theme-is-not-responsive-2

https://wordpress.org/support/topic/customizr-site-too-big-feature-buttons-and-sidebar-not-in-correct-location

Need advice on whether it is a Theme or Plugin fix needed

**Comment by eri-trabiccolo** [comment]
I've also replied to other users with a similar issue (always that plugin conflict), so thanks for reporting here officially!
Anyway more than a conflict I think it's a misbehavior of that plugin. I don't know why they assume they can style that way a common (bootstrap) class like `container`.
I do not think we can do something if not, in presence of that plugin try to load their style before our theme's main style. So we override their rules. But still, they *shouldn't* have such a rule, they should confine their rules to their components. A Theme defines the general appearance a website will have, a plugin shouldn't be that intrusive.
IMHO, let's see what @Nikeo thinks about that.

**Comment by rdellwebworks** [comment]
As Theme Author, does @nikeo have more authority to report to the Plugin author, or escalate to wp.org?

**Comment by Nikeo** [comment]
Hi, did not dive into the issue, but based on what @eri-trabiccolo says, if they style directly the container class, this is not a very good practice, 100% agree.

Anyway, I'll report this to the plugin author and we'll see how we can do about this conflict.

@rdellwebworks can you confirm that the 3 forum issues where all happening whith the following combination : 
* Customizr
* SiteOrigin Page Builder plugin
* Ultimate Addons for SiteOrigin plugin

Thanks for reporting this !

**Comment by rdellwebworks** [comment]
Confirmed

**Comment by rdellwebworks** [comment]
This has appeared this afternoon in https://wordpress.org/support/topic/customizr-site-too-big-feature-buttons-and-sidebar-not-in-correct-location

Hi @ArieltheHuman @rdellconsulting

Andrew from SiteOrigin support here. Sorry to hear you've run into a problem. The author of Ultimate Addons has made changes to his plugin based on my feedback in the past so hopefully he can correct.

If something directly related to a SiteOrigin plugin comes up, don't hesitate to let me know.

Hope you're able to resolve.

**Comment by eri-trabiccolo** [comment]
Mmm, any news on this?
We really can't to that much on our side, if not that thing with the CSS order .. which I'm not sure will work anyway as I'm not sure we use the same CSS rule specificity (and I'm not sure we want to make it stronger ...:|)
