### ISSUE TITLE
Fix themes.php?page=welcome.php

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#391]
In about Customizr and Help, the 3 columns layout  are not styled anymore.

**Comment by eri-trabiccolo** [comment]
Mmm,
I probably never looked at those .. what it should look like?
Why it doesn't work anymore, was based on a built-in embedded wp style?

**Comment by Nikeo** [comment]
Yes it was based on a built-in wp admin style 
feature-section col three-col

**Comment by eri-trabiccolo** [comment]
Ah ok was looking at the Pro About and couldn't see those classes. :).

**Comment by eri-trabiccolo** [comment]
Mmm I see things are changed in the wp style, works fine with old wp
I think we need to fine tune the style with our custom css. (margins and borders stuff)
Anyway I push a PR just for the column "issue", I'll left to you the real styling part 'cause you're the boss :P
