### ISSUE TITLE
Remove the additional 'Back to Top' Link when Back to top arrow is enabled

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#394]
This was already talked about in a past issue I think.
Anyway, this was reported here : https://wordpress.org/support/topic/additional-back-to-top-link-after-update?replies=2

**Comment by eri-trabiccolo** [comment]
Yeah but the thing is.. what do we want to do? Leave that space empty?
I already can see request to "fill" that area..
Anyway .. FC, right?

**Comment by Nikeo** [comment]
Yes this will be left empty.

Why FC ?

**Comment by eri-trabiccolo** [comment]
More customizations of the footer :)
Ok so free. Just a checkbox.

**Comment by Nikeo** [comment]
no option needed there. The additional back to top has to be removed when back to top arrow is on

**Comment by Nikeo** [comment]
with a filter or whatever is available :)

**Comment by eri-trabiccolo** [comment]
ahh so with a notice.
Ok, hopefully we'll not have complains.

**Comment by Nikeo** [comment]
forget about the notice too !

**Comment by Nikeo** [comment]
I don't think there will be a complaint's tsunami about this. It just makes sense

**Comment by eri-trabiccolo** [comment]
ahah ok, you optimistic giant you.
