### ISSUE TITLE
template_redirect not fired in particular contexts leads to no "head" loaded

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#395]
I have a little issue, wp_head() function located inside tc_head_display() function in TC_header_main class in your theme that is loaded using 'template_redirect' hook. But Multisite wp-signup.php use 'wp_head' hook that does not fire as 'template_redirect' does not fire in signup page. Can you provide a workaround? I have already done in some other way but i think it need to be done in core theme.

if you see template-loader.php, you will see do_action( 'template_redirect' ); is located inside if ( defined('WP_USE_THEMES') && WP_USE_THEMES ) condition. and WP_USE_THEMES defined in index.php but wp-signup.php is accessed directly, so in wp-signup.php template_redirect is not fired.

Thanks.

https://wordpress.org/support/topic/multiste-signup-problem?replies=6

**Comment by eri-trabiccolo** [comment]
see my mail:
wp-signup issue: thoughts 
06/10/2015

:)

**Comment by Nikeo** [comment]
Hello Nico,
I've read this -> https://wordpress.org/support/topic/multiste-signup-problem
(haven't opened a github issue 'cause I saw you're on it)
And yes that guy has "some rights" 'cause template_redirect actually isn't fired in wp-signup.php (and wp-activate.php). [Consider that when not in multisite they're both redirected on wp-login.php that doesn't retrieve the theme's header and footer]
We might use wp or wp_loaded
(other callbacks hooked to template_redirect are relative to the headings, post metas and slider, so we can leave them as they are now)

But I remember you talked about allowing no header and no footer (read "landing pages") with contx.
Well the contx will not depend on the hook template_redirect, and we really never use php templates :D so we can always use the filter you provide here:
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-header-header_main.php#L55

Otherwise, if you want to be able to use that filter in php templates, we can consider to split the hooks further more and place the hooks below this line -> https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-header-header_main.php#L53
in a callback hooked to *our* __before_body
As alternative we can fire re-hook our callbacks just when on that page,

isset( $pagenow ) && 'wp-signup.php' == $pagenow;
['wp-activate.php']

Also, we can make the wp-signup page more a "customizr" page by using the wp-signup.php action hooks:
before_signup_form
after_signup_form

to wrap the form into the main_wrapper , as we do with woocommerce (remember that we have these useful methods :P ->
https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-plugins_compat.php#L593
https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-plugins_compat.php#L610
)
[though I'm not sure where to place this "compat" code, I do not want it in the compat plugins class, maybe in fire-init would be fine]

Finally, there's a global discussion about templating those pages:
https://github.com/WordPress/WordPress/commit/ab5ea42aa2702756c1c1202c4ca7857c425e7339
https://core.trac.wordpress.org/ticket/21712
https://core.trac.wordpress.org/ticket/17948

Let me know what you think, when you want/can, or if you want me to open an issue where I would copy the whole email :D

Hope I haven't said so many bullshits :D

**Comment by eri-trabiccolo** [comment]
Ok I will never send you private emails, I'm also thinking about denouncing you for this..
clearly when I say:
> Let me know what you think, when you want/can, or if you want me to open an issue where I would copy the whole email :D
it's implied that that sentence itself + the next would not have been included!
For the record, I never hope that 'cause I know that I never say bs! :P

**Comment by Nikeo** [comment]
oh do you really want me to remove some parts ?

let me know :)

**Comment by eri-trabiccolo** [comment]
Naa, I could remove those parts as "collaborator", I have the capabilities :)

**Comment by Nikeo** [comment]
ah ok :)

well, to follow up with this, in the near future, the tc_display_header filter will be replaced by a more standardize way to render a given view. So We could test replace template_redirect by wp for this particular case (head) I think. => I don't think it could lead to any regression but this will have to be tested.

**Comment by eri-trabiccolo** [comment]
So ok let's go with `wp` hook and let's make some tests, more with the plugins we support like woocommerce, bbpress and so on.
Let's see what happens.
