### ISSUE TITLE
Slider images 'jumping' (resizing) on initial load ...

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#399]
## Reported by a user : ##
> I have recently updated a site to the latest Customizr V3.4.14 theme.
> This problem is predominantly evident when using Safari, but I've also noticed it happens when using Chrome on an iPhone 5 too ...
> Pictures that have been added to a slider at the top of the page (any page, including the home page), seem to 'jump' initially as the page is loaded by the browser. Seems the graphic is first rendered in a much smaller size, and then shortly after is re-sized to its proper dimensions.
Sometimes this requires a 'page refresh' to clear the problem.

> I have also noticed that the graphic sometimes does not render at all initially, requiring a reload action to display correctly.

> This problem is not only Safari specific ... seems to also affect Chrome when viewing on iPhone or iPad platforms. When viewed on a desktop, Safari is the only browser I've tried that shows this problem.

**Comment by eri-trabiccolo** [comment]
Bug?
The resizing (jumping)is about the centering  - that's why you added the loading icon, isn't it?
It can be even worse with retina enabled.
The problem could be retina + our centering script, anyway I have an hd smartphone, then it retrieves retinas without any big issues (we'll always see a little jump).

**Comment by Nikeo** [comment]
Fixed by latest PR from Rocco https://github.com/presscustomizr/customizr/pull/481

**Comment by eri-trabiccolo** [comment]
If users use the loading icon .. yes :D

**Comment by Nikeo** [comment]
ah yes, but not enabled by default.
So should re-open this issue to fix the problem when loading icon not on.
I'm open to any suggestion :)

**Comment by eri-trabiccolo** [comment]
I really do not think we can do that much. When an image isn't in the doc jquery/javascript isn't very able to evaluate it.
I think I have to look more into this and come with a definitive answer, so we can tell user that .. is impossible and they have to use the loading icon :D
