### ISSUE TITLE
Compatibility with Disqus : bubble comment click doesn't scroll in single posts

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#402]

**Comment by eri-trabiccolo** [comment]
The only thing, IMHO, we can do is filter the the comments link and set it to #disqus_thread (main disqus wrapper).
Though there are users who have some addons which makes that not enough, since they appear before the actual list of comments.
Honestly I don't think we should dig to find a way to go into an iframe anchor (wonder if it's really possible).

**Comment by eri-trabiccolo** [comment]
Looked more into this.
We cannot use the above method as the disqus js (remote) as soon as it's loaded scans the body and replaces the comment bubble span (which is inside a link with a hash == 'disqus_thread' ) with a default text like "N comments". It doesn't do that if the link has a special attribute set `data-disqus-identifier`, which means something to disqus that I don't know, or better, I can figure it but I don't know how discuss can interpret it if we set it to something (just as an hack).
So my proposal is:
As disqus filters the wp `comments_template` I suggest to do this, under opportune conditions (check on whether or not the disqus template will be loaded)
a)we hook to that filter too with a lower priority and wrap this template into a div with id `tc-comment-title` (or use another name more descriptive for this purpose, then filter also the anchor link)
or
b) hook to the action `__after_loop` (comments have priority 10) with priority 9 and 11 printing a starting and ending div wrapper with the id as in the bullet a)
Even if I generally prefer to not filter big stuff (which anyways are already filtered by disqus itself), I think bullet a) is the better solution as, in our system, the comments can be moved unhooking and re-hooking `tc_comments` callback. 
An hybrid solution will be, change the `tc_comments` callback so it doesn't directly call the `comments_template` function, but another action hook, e.g.:
`do_action('tc_comments')`
to which a callback which calls `comments_template` is hooked.
This way we can implement bullet b)

The latter would be my preferred solution, to be honest, but as the `hairy_views_&_co` (:P) is on its way .. I think I'll stick to bullet a) until the new framework will be ready (maybe this is those kind of case which have to be considered, if not already, when fine tuning it).

Let me know if you have anything against this ;)

**Comment by eri-trabiccolo** [comment]
I went for an alternative to b)
firing two actions before and after the `comments_template` is called, using them as hooks for our wrapper.
