### ISSUE TITLE
Jetpack Sharing buttons => Images will not be parsed for Smartloading

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#414]
This is because their sharing button (added to the_content with a filter ) contains a "data-src" which makes our parser exit.
https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-utils.php#L121

The thing is that to make our smartload correctly work with their photon, we did this ->
https://github.com/presscustomizr/customizr/pull/335

So I don't see a global solution which will imply having smartload when both are on if not
unhook and re-hook their sharing filter callback.
But:
1) I don't like mess with other plugins rules, they might have a reason we don't know
2) I don't think our "exit strategy" (:)) for the img parser is strong enough, we might have problems with other plugins which just use that "data-src" string for something else, or for the same reason dunno.
I think we have to handle the "not data-src" piece inside the preg_replace_callback, as we do with "data-smartload"
What do you think?

Look that this doesn't mean that our smartload breaks something, it just doesn't work, the image is displayed naturally.

**Comment by Nikeo** [comment]
I think it's better to handle the data-src case image by image (in the regex_callback) instead of globally.
So yes I agree with your PR
