### ISSUE TITLE
Custom taxonomy name not displayed in archive title

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#416]
## Problem
A custom taxonomy name won't be displayed in the archive page title in some cases.
This has been identified when creating a custom taxonomy with the plugin Custom post type UI
https://wordpress.org/plugins/custom-post-type-ui/
And adding this taxonomy name to a search filter with the plugin Search Filter http://wordpress.org/support/plugin/search-filter

## Online example
http://grqaser.org/language/en/format/audiobook/).

## Screenshot
![2015-11-24_11-21-07](https://cloud.githubusercontent.com/assets/3038156/11363994/91f8f04a-929d-11e5-8767-ae1dfd941e20.png)

**Comment by eri-trabiccolo** [comment]
I'm glad you're improving your design skills, the problem is that the issues this way are beautiful and I'm tempted to leave them open :P

**Comment by Nikeo** [comment]
:)

**Comment by eri-trabiccolo** [comment]
Were you able to reproduce it?
I tried making a "movie" cpt + "actors" tax and I see "Actor: Actor1" as archive title.
Didn't test the search plugin atm.
Also we display tax archive titles here:
https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-headings.php#L422
The syntax "Tax singular label: Tax_element" is typical (I mean that "`:`" ) of:
`get_the_archive_title()`
https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/general-template.php#L1244
Looks like `$tax->labels->singular_name` is empty.. don't think could be our fault ..

I cannot see how our own "code" for archive titles cannot produce "blank space" + ":" .

Might be a conflicting plugin too (that translation plugin ?.. dunno which one).
If you want give me the link of the support topic and I'll try to see if I can get more info from the user.
But I inform you, the first thing I'll ask is:
"Did you try with a default theme like twentyfifteen? Can you reproduce it?" :D

**Comment by Nikeo** [comment]
I can't share the link because it's a private conversation.
Anyway, I'm trying to get more details from the user and have asked your suggested question :)

**Comment by eri-trabiccolo** [comment]
:)

**Comment by Nikeo** [comment]
not reproductible
