### ISSUE TITLE
Sticky header and big height dropdowns

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#418]
At the moment we handle the case when the `.nav-collapse` overflows the viewport in mobiles here -> https://github.com/presscustomizr/customizr/blob/master/inc/assets/js/parts/bootstrap.js#L1653
But this should be valid also for `.dropdown-menu` in desktop mode.
What do you think?

**Comment by Nikeo** [comment]
Can I reproduce this problem simply with a long menu ?

**Comment by eri-trabiccolo** [comment]
Well, for example:
(this is an edge case just to show the potential issue)
http://prntscr.com/96pcvi

**Comment by Nikeo** [comment]
ah ok thanks got it. Do you think we can apply the same kind of fix for desktop viewport then ?

**Comment by eri-trabiccolo** [comment]
I think we can try to force the "dropdown to viewport" thing when sticky enabled. But that's an option for mobiles now, might be confusing adding another option.. maybe we can do that by default without caring too much about reactions :D It's an edge case anyway.
Mmm and now that I think about it will involve nested submenus (which have a slight top offset). Have to see.

**Comment by Nikeo** [comment]
yes I agree, that's kind of an edge case. Wasn't reported that much from what I have seen?
Did you already see this problem reported somewhere or you found it by yourself ?

**Comment by eri-trabiccolo** [comment]
Never reported :)
Just thought at it when doing the wc cart stuff. Storefront approach for the list of products in the dropdown is to limit it to a max-height of 15em (which I stole).
