### ISSUE TITLE
WPML Compatibility in admin : slider details (in the slides table) are not translated when editing a post or page

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#419]
When helping a user to translate a slider, I discovered a problem.

In the back office, the slider details displayed in the slides table are displayed translated when editing an attachment. Which is fine.
![slider_details_translated_in_admin](https://cloud.githubusercontent.com/assets/3038156/11417529/31ff9596-9418-11e5-9af6-d2ae05723e5c.png)

But when editing a page or a post on which we've added a slider, the translation is not reflected
![slider_details_not_translated_in_admin](https://cloud.githubusercontent.com/assets/3038156/11417540/402981fe-9418-11e5-80db-472560a56e18.png)

**Comment by eri-trabiccolo** [comment]
Ah, yeah : https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-plugins_compat.php#L556

**Comment by Nikeo** [comment]
ok. thanks that was fast.
did you test it ? :)

**Comment by eri-trabiccolo** [comment]
Yes I did.
Looks like it works fine. But your double check won't hurt. :P

**Comment by Nikeo** [comment]
ok thanks :P
