### ISSUE TITLE
Reponsive settings, better notices?

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#423]
That's what we say, for some options:
Sidebars reordering:

>  Dynamic sidebar reordering on small devices
> 
> Activate this option to move the sidebars (if any) after the main content block, for smartphones or tablets viewport.

and Secondary menu moving:

> Choose a mobile devices (responsive) behaviour for the secondary menu.

Maybe we should say what we mean with "mobiles/smartphones and tablets viewports" (ww<768px)
'cause often users get confused as iPads even if are tablets don't match our condition.
Otherwise, especially in the Secondary menu moving, we might always do it when "is_mobile".

**Comment by ghost** [comment]
enhanced since then
