### ISSUE TITLE
MENU : Padding bug for the first menu item on responsive mode

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#430]
As reported by a user : 

> Go to Customer > Header > Navigation Menus, select Regular (Horizontal) as the main menu design and then select menu on the left as the menu position. The menu on larger screens positions itself correctly. Shrink the browser down to hit the media breakpoint and then open the navbar. The first menu item is pulled left while the rest have some padding on the left.

I've been able to replicate the issue on chrome latest version (but it's not a browser issue anyway :) )

**Comment by eri-trabiccolo** [comment]
This is old, we discuss it ...
Didn't we fixed it already? There might be some regress at some point ..
(I'm just making a fix for the dropdown js, will look at this new issue later)

**Comment by eri-trabiccolo** [comment]
Btw this is issue is here since 1 year ago, I thought it was by design :) Has been reported several times :)
