### ISSUE TITLE
RTL colophon issues

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#440]
1) RTL colophon blocks are not in the right order.
RTL Colophon should look like the mirrored version of the LTR one.
So socials on the right and back to top on the left (as well as the btt button), atm it looks like this:

fig a)
![rtl-colophon](https://cloud.githubusercontent.com/assets/7689242/11527880/cb010926-98e3-11e5-9ce6-78eb56be0961.png)

This is because when RTL we reverse the blocks order with php but we also set the bootstrap floating direction to right => annihilation
Another side effect is that if we remove the btt column (which is what we want to do when the btt button is enabled) you'll see the following:

fig b)
![rtl-colophon-no-btt](https://cloud.githubusercontent.com/assets/7689242/11528131/27c6a89a-98e5-11e5-9816-dd417201e751.png)

This is also because the social-block still keeps its `pull-left` class, so we'll have
span3(pull-left) - span3(nothing) - span6(float: right), while it should be
span3(nothing) - span6 - span3(pull-right).

2) Credits elements are messy (see fig a). "Powered by W" should be on the left and "Customizr" on the right. Also "Designed by Press Customizr" as it's composed by two "blocks" ("Designed by" and "Press Customizr") should look like "Press Customizr Designed by"

**Comment by eri-trabiccolo** [comment]
This is how it looks like with the proposed PR:

![rtl-colophon-fix](https://cloud.githubusercontent.com/assets/7689242/11529473/95776c00-98ed-11e5-96b1-1facf91c92cc.png)

**Comment by JTS-IL** [comment]
:-)
It was one of my future issues, happy to see someone thought about it too.

**Comment by eri-trabiccolo** [comment]
:D 
Glad to see you agree with it, thanks for your feedback I was a bit worried about it :)
