### ISSUE TITLE
Alternate layout/featured pages thumb links not working in ie<11

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#450]
This is an old issue we partially covered with the following snippet back in the past:
http://presscustomizr.com/snippet/allow-thumbnails-links-ie10/

We never embedded it in the theme. Also the alternate thumb html has been changed meanwhile and that snippet doesn't suite it anymore + it might (I'm pretty sure it does though haven't tested it) with the centering js.

We also don't have to forget that the snippet in question got rid of the round-divs which was fine for ie<9 (as it doesn't support border-radius - rounded was the only available shape at that time) but even if it exposes the links for ie<11 it got rid of the expansion effect and the shape for 9<ie<11.

We should look for a different solution and if we cannot we have to decide if we want to keep the things as they are now (so privileging expansion on hover and shape over the linking feature) or doing vice-versa (link allowed, but no shape/expansion).
I'm sure we're just missing something very small and subtle to achieve that as we the grid works fine (while I'm writing I think I found it, but will keep the secret till it passes a more proper test :P)

p.s. reported
https://secure.helpscout.net/conversation/146291027/4515/

**Comment by denzelchia** [comment]
Hi Rocco,

Thank you very much for helping me reply the support thread.
And Thank you for the explanations too.

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
:)
I did I mess, I was sure I was replying to you :)
For IE10 then the issue disappear if we force the `.round-div` background to "transparent" but only with a rule like the following:
`background: rgba(0,0,0,0) !important;`
Anyway for ie10 looks like the issue it's just about the background, clearly an IE issue, ie9 (probably) and below (sure) need some other adjustments.
The "funny" thing about the background + featured pages unlimited is that I couldn't reproduce the issue on my end 'cause that rule (rgba background), is as matter of fact, present in the fpu CSS.
See addons/fpu/front/assets/css/fpu-front.css on line 129
`background: rgba(0,0,0,0) !important;`

I was testing the issue in dev mode (meaning WP_DEBUG set as true) and I couldn't reproduce it with fpu, because as you can see that rule exists (in the non minified CSS).
The problem is that when you're in production (WP_DEBUG false) you load the min style, which is created by grunt, and that rule becomes:
`background: 0 0!important;`
Looks like the rule above isn't the same as the other one for IE10 and below.

Very weird :)
