### ISSUE TITLE
Wordpress 4.4 responsive images related issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#452]
We might have other problems with this new feature as you can see here:
https://wordpress.org/support/topic/remove-srcset-from-slider-images-wp?replies=2#post-7757888

I suggested a small snippet. I went for that solution 'cause we could even use the filter
`wp_get_attachment_image_attributes` and remove `srcset` and `sizes` attributes but atm we don't really have action hooks which allow us to limit the "reponsive images disabling" just for the slider.

I think will be better add at least one option among the `Image settings` to disable the reponsive images feature for the slider (or maybe also for the grid(?), in this case among the grid options).

Till we make a decision on this and the new theme's version will be released, wouldn't be good create a blog on presscustomizr.com with that snippet?

p.s.
do you like the github Labels' rainbow I created for this issue? :P

**Comment by Nikeo** [comment]
Yep good point.
So the idea would be to allow users to disable the defaut WP 4.4 responsive image feature ?
For slider and grid ?
Sounds good.

I kind of like your art creations using github's label. quite unique :)

**Comment by Nikeo** [comment]
yep go ahead for the snippet publication too

**Comment by Nikeo** [comment]
About the slider, I wonder if this "disabled default resp WP 4.4" option should even be enabled by default ? At least if the sider is in full width mode...need to test this.

**Comment by Nikeo** [comment]
( i need to go Rocco, I'll follow up tomorrow on this) => I'll try to push a new release tomorrow

**Comment by eri-trabiccolo** [comment]
Ahah ok :D 
I think should be enabled by default for the slider.
We have to better look into this anyways, we have to see if we can act on these responsive image sizes so to fit them to our needs (see sliders + custom heights, our responsive heights for slider and grid in smal viewports and so on).

p.s.
I'll be not able to push the "round-div" thing for tomorrow, but probably we'll have some more time for that till the new version will go live.

**Comment by eri-trabiccolo** [comment]
Ok Nico,
I think we should provide 2 options:
1) Disable WP responsive image feature for the slider
2) Disable WP responsive image feature for the theme's thumnails

This 'cause we can have the same issue with the grid (mostly for 1 column layout), but also for the single post thumbnails or rectangular thumb in post lists.
So where to place these options, under Image Settings? Or maybe we can re-introduce the "Responsive settings" panel ?

**Comment by Nikeo** [comment]
Let's add it after the existing settings in customizr> globa settings > Image settings
![2015-12-10_09-44-09](https://cloud.githubusercontent.com/assets/3038156/11710886/d57d9e1a-9f22-11e5-9d05-6c8677b78825.png)

With a title : Responsive settings, and the 2 following options, disabled by default 
* Enable WP responsive image feature for the slider
* Enalbe WP responsive image feature for the theme's thumbnails

What do you think ?
Can you push it today ? (I'm working on the new release today and would like to push it by the beginning of the afternoon)

Let me know if possible

**Comment by eri-trabiccolo** [comment]
Ok fine.
I think I can.
I'm on it.

**Comment by eri-trabiccolo** [comment]
Can you take care about the notices if any? :D

**Comment by Nikeo** [comment]
yep I'll do it.
Thanks, happy coding :)

**Comment by eri-trabiccolo** [comment]
Let me know what do you think, especially for the "trick".
Look that, IMHO, this should be ported for FPU too. I can take care of this, but some specs will be needed ;)

**Comment by eri-trabiccolo** [comment]
What about FPU then?

**Comment by Nikeo** [comment]
I'm looking at the "trick"
//trick, will produce an empty attr srcset as in wp-includes/media.php the srcset is calculated and added
+        //only when the passed srcset attr is not empty. This will avoid us to:
+        //a) add a filter to get rid of already computed srcset
+        // or
+        //b) use preg_replace to get rid of srcset and sizes attributes from the generated html
+        //Side effect:
+        //we'll see an empty ( or " " depending on the browser ) srcset attribute in the html 
+        //to avoid this we filter the attributes getting rid of the srcset if any.
+        //Basically this trick, even if ugly, will avoid the srcset attr computation

**Comment by Nikeo** [comment]
not that "ugly" and well commented so let's go for it. (and keep the comments also in FPU so that we know what why we had it :) )

**Comment by eri-trabiccolo** [comment]
ok :)
(mm to avoid a new PR you can copy the same comment here -> https://github.com/presscustomizr/customizr/blob/dev/inc/parts/class-content-slider.php#L133)

**Comment by Nikeo** [comment]
ok done

**Comment by eri-trabiccolo** [comment]
Mmm, forgot to ask.
I'll add an option for FPU among its tb settings.

**Comment by Nikeo** [comment]
which settings => what is tb for you ?

**Comment by eri-trabiccolo** [comment]
:) 
I meant all those options "image" related, so those which depend on `tc_show_fp_img`

**Comment by Nikeo** [comment]
yep make sense :)

**Comment by eri-trabiccolo** [comment]
Mm,
I wonder if wouldn't be better to make this not an option for FP(U) and alternate layout, 'cause we really don't want this. Anyway 4.4 customizer is really fastttttttt so adding this option(s) isn't really an issue :)
