### ISSUE TITLE
Logo customizer options : hide logo related options when no uploaded logo

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#454]
Those 2 options should be hidden when no logo has been uploaded by the user yet 
- Force logo dimensions to max-width:250px and max-height:100px
- Sticky Logo Upload (supported formats : .jpg, .png, .gif, svg, svgz)

**Comment by JTS-IL** [comment]
If you're already taking care of the logo - may I suggest something :
add an option to select the logo from media library. It's most relevant when changing existing site from any theme to customizr, or importing from other WP site.

**Comment by Nikeo** [comment]
good point Yaacov I agree. Will open a new enhancement issue about this.

**Comment by JTS-IL** [comment]
:-)

**Comment by eri-trabiccolo** [comment]
- Sticky Logo Upload (supported formats : .jpg, .png, .gif, svg, svgz)

this is actually unrelated, users may have a sticky logo but not a logo.
I remember some users using this combination.

I can do this enhancement while doing this -> https://github.com/presscustomizr/customizr/issues/366
