### ISSUE TITLE
Border bottom in widget lists

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#459]
We should limit the CSS rule which applies a border bottom to the widget list items in the #main-wrapper just to the sidebars.
This cause there are several plugins which use the widget system putting widgets inside the content (see page builder & co).
What do you think?

https://secure.helpscout.net/conversation/149415956/5002/?folderId=607546

**Comment by Nikeo** [comment]
oh yes! this should be limited to sidebars (and footer)

**Comment by eri-trabiccolo** [comment]
Mmm, actually we have no rule for the lists in the footer.
In the demo the border is for a specific widget type:
`.widget_recent_entries li`

so, do you mean we should extend the rule I referred to the footer widgets too?

**Comment by Nikeo** [comment]
only if necessary

**Comment by eri-trabiccolo** [comment]
I forgot you're an engineer, I should expect that answer. I can reply with "It depends..." :P 
Ok so the original rule doesn't involve lists in footer widgets, specific widgets are treated case by case, so I'll push a pr which just changes the rule from being applied in widgets inside `#main-wrapper` to those inside `.tc-sidebar`
:)

**Comment by Nikeo** [comment]
ah ah.
It was mainly the reply of a guy who did not look into it and relied solely
on your insights to help you take a decision...:)
*only if necessary* suddenly appeared to me to be the most appropriate
answers :) :)

**Comment by Nikeo** [comment]
thanks for fixing this

**Comment by eri-trabiccolo** [comment]
:D
