### ISSUE TITLE
Custom fonts not working in Firefox or IE

### ISSUE THREAD

**Issue by walterwhiteknives** [presscustomizr/customizr#460]
I just noticed today that the custom fonts aren't working on my site. WalterWhiteKnives.com

I tried reselecting them in the Customizr settings and the fonts work in the customized area but don't show up in a regular browser window.

**Comment by Nikeo** [comment]
Hi, sorry for the extremely late reply !
Did you find a solution? Does the problem still occur with the Customizr theme ?

Thanks :)

**Comment by walterwhiteknives** [comment]
Hey Nikeo. It was the last time I used it. I finally just decided to switch themes. Great theme though. Thank you for the response.
