### ISSUE TITLE
Link the whole slide and slide's caption

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#466]
Do we want to make it part of the link when linking the whole slide?
At least when there are no buttons?

https://secure.helpscout.net/conversation/150034873/5095/?folderId=607546#thread-388720202

**Comment by eri-trabiccolo** [comment]
What we can do, to keep both the button and the caption link, is put a link in the caption and play with the position and z-index, something like:

`a.tc-slide-caption-link {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 99;
}

.carousel-caption .btn {
    z-index: 100;
    position: relative;
}`

makes sense to me. Opinions?

**Comment by eri-trabiccolo** [comment]
Mmm closed why? :D

**Comment by rdellwebworks** [comment]
https://wordpress.org/support/topic/slider-links-not-working-1

Here's a post that would lead to reopening this Issue?
