### ISSUE TITLE
Possible compat. issue with SEO plugins ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#468]
As reported by a user

> Hi! I tried Yoast but the meta description box was missing so I switched to SEO Ultimate. It seems some functions of SEO Ultimate won't work as well (e.g. automatically adding site name to title) and the social sharing buttons that can be used with it (AddThis) also don't appear on my site.

**Comment by eri-trabiccolo** [comment]
Sorry I don't get the yoast issue.
Will look into the SEO Ultimate one later.
