### ISSUE TITLE
Iphone6 in portrait and sidemenu

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#469]
A singular issue has been reported involving iphon6 just in portrait and the sidemenu when opened:
https://secure.helpscout.net/conversation/150477050/5182/?folderId=607709

Basically the sidemenu, when shown, looks like highly zoomed and the navigation becomes impossible.
![image2](https://cloud.githubusercontent.com/assets/7689242/11874255/fdce6220-a4de-11e5-97cb-36268811ccff.png)

The most weird thing is that the user isn't able to reproduce the issue on the demo website.

I'm not able to reproduce it with the google-chrome emulator

**Comment by giorgioriccardi** [comment]
I tested on my boss i-Phone 6 and it did not show any problem; I tested several combinations as well...
![img_0052](https://cloud.githubusercontent.com/assets/3901192/11883177/eec741a2-a4c5-11e5-939d-45a94742db7c.PNG)

**Comment by eri-trabiccolo** [comment]
Thank you Giorgio :D

**Comment by eri-trabiccolo** [comment]
The issue is confirmed using an iphon6+ on the user's website.
Still unable to understand the reason though.
Will try suggesting a CSS zoom forcing ... mah, let's try

**Comment by Nikeo** [comment]
could not replicate
