### ISSUE TITLE
Closing main-wrapper div html comment, can be seen as a server directive

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#470]
Issue raised here:
https://secure.helpscout.net/conversation/150627404/5201/?folderId=607709
error message:
[an error occurred while processing this directive]

I'm unable to reproduce it but I can see why it might happen:
http://httpd.apache.org/docs/1.3/mod/mod_include.html

I see in the user's page giving that error that:
    </div>

gives no issues. So we can safely use that form.

**Comment by Nikeo** [comment]
mmm good to keep in mind. Thanks for the fix
