### ISSUE TITLE
FW0001 (Doc) Add Slider to Archive/404 pages

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#482]
https://wordpress.org/support/topic/slider-on-archive-page

User has provided a raw solution in the post

**Comment by eri-trabiccolo** [comment]
Not sure what the user means, or .. what do you mean with "user has provided a raw solution in the post" ?
The snippet he provides is a merge of the snippet he linked (provided on presscustomizr) + some "errors" like:
`add_filter('tc_show_slider' , '__return_true' );` (force the slider everywhere)
but
`add_filter( 'tc_show_slider' , 'tc_show_slider_in_categories' );
function tc_show_slider_in_categories( $bool ) {
return ( is_category() && array_key_exists( tc_get_cat_slug(), tc_get_slider_name_by_cat() ) ) ? true : $bool ;
}`
force the slider only in some categories.
Also the full width is achievable with a method provided:
`//display in full width
add_filter( 'tc_slider_layout' , 'tc_force_full_width' );
function tc_force_full_width( $original_layout_value ){`

Where's the issue?

**Comment by rdellconsulting** [comment]
The User provided a solution which you’re confirming is unfit for general use. So the Issue to me is:

Can you add Slider to Archive/404 pages, and could it be an Enhancement or Documentation solution?

**Comment by eri-trabiccolo** [comment]
Ahh.. so the thing is that the snippet is for categories but not for all the archives (or 404), didn't get, sorry.
Mmm ok I got it.
I think we'll see if we can add a new snippet for that in the coming months (we are about to make some deep core code changes), but not really sure we'll do that :D
Thanks for reporting this Dave.

**Comment by Nikeo** [comment]
Hi Dave,

To the question : Can you add Slider to Archive/404 pages, and could it be an Enhancement or Documentation solution?

The answer is : this option is not available yet. Of course it's easy to implement for a developer.
As Rocco mentionned it, some major improvements are coming that will allow to design any pages as a if it was a standalone website.
I close this for now.
