### ISSUE TITLE
FW0002 (Issue) Make All Posts Lists grid style

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#483]
https://wordpress.org/support/topic/make-all-post-lists-grid-style

User identified idiosyncratic use-case

**Comment by eri-trabiccolo** [comment]
Theme's grid is possible only with standard wordpress post lists (archives, search results..).
That's not an issue. Plugins can use their custom query/loops, how can we know that? The same happens with the alternate layout. The same will happen with whatever theme styling the lists of posts with their own structure. Most of the things we do to "build" the grid (or the alternate layout) are fired with our internal action hooks ( `__before_article`.. `__before_loop`) etc. etc.
Anyway in the future there will be an easy way to build grids with a shortcode, which still doesn't mean external plugins list of posts will be shown with our grid.
