### ISSUE TITLE
FW0006 (Issue) Modals problem

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#484]
https://wordpress.org/support/topic/plugin-conflict-108

Plugin conflict due to use of Bootstrap 2/3

**Comment by eri-trabiccolo** [comment]
Don't think we can do anything about that.. honestly.
Bootstrap3 cannot be used along with bootstrap2.
Two instances of Bootstrap2 shouldn't cause an issue with the modal .. though surely will cause issues with dropdowns and slider (as we have customized those "bootstrap plugins").

**Comment by rdellconsulting** [comment]
What to post back, especially as @soykatorce is reporting issues with his live customer?

**Comment by eri-trabiccolo** [comment]
soykatorce has already solved it in his topic:
https://wordpress.org/support/topic/version-v3416-modals-not-working?replies=10#post-7796333

Generally we cannot do that much, they can disable the culprit plugin or we can see if we can provide a code to avoid the plugin loading its bootstrap2 ( rare cases ) Anyway it mostly depends on the plugin + the plugin's authors can provide the code too -> not really our business.
