### ISSUE TITLE
FW0007 (Issue) Woocommerce Child Theme error

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#485]
https://wordpress.org/support/topic/child-theme-179

Woocommerce Child Theme problem

**Comment by eri-trabiccolo** [comment]
That's the same of this:
https://wordpress.org/support/topic/erroneous-character-causing-syntax-unexpected-token-error?replies=9

User hasn't replied to my last answer.
I'm inclined to think the issue doesn't come from our contents, must be something he introduces in his child-theme.
Cannot do anything else but wait for his feedback.

**Comment by eri-trabiccolo** [comment]
I still think is a user's problem editing files with notepad++ with uft8+BOM
We cannot do anything.

**Comment by rdellwebworks** [comment]
No response from User so Closing
