### ISSUE TITLE
FW0008 (Issue) SEO Best practice H1/H2

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#486]
https://wordpress.org/support/topic/carousel-slider-change-h1-to-h2

Recurring Issue. Can we get a definitive SEO policy and document it?

**Comment by Nikeo** [comment]
This is not perfect but not bad for SEO
https://www.youtube.com/watch?v=GIn5qJKU8VM
http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824
