### ISSUE TITLE
FW0009 (Doc) Out of date doc accessible

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#487]
Documentation relating to setting up Menus is accessible via Search.

Search for 'Menus' gives:
Customizr Theme Options : Front Page (145) Correct
Customizr Theme Options: Header settings (101) is out-of-date

**Comment by Nikeo** [comment]
Which search it is ? 
Thanks !

**Comment by rdellwebworks** [comment]
http://docs.presscustomizr.com/

#1 is correct
#6 is out-of-date

**Comment by Nikeo** [comment]
OK Thanks

**Comment by Nikeo** [comment]
updated in the doc tasks
