### ISSUE TITLE
FW0011 (Issue) Feature image doesnt work after wordpress 4.4 update

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#488]
https://wordpress.org/support/topic/feature-image-doesnt-work-after-wordpress-44-update

Open Graph issue?

**Comment by eri-trabiccolo** [comment]
Is it about facebook?

**Comment by rdellconsulting** [comment]
Maybe Denzel can add here as he managed it.

**Comment by Nikeo** [comment]
can't replicate this.
We'll see if other users report it
