### ISSUE TITLE
FW0012 (Issue) Woocommerce showing 2 logos

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#489]
https://wordpress.org/support/topic/it-dysplays-two-header-logos

**Comment by eri-trabiccolo** [comment]
Cannot reproduce this issue.
Two logos?
Cannot see the user's website either as it's "locked".
Anyway, most likely depends on something the user has in its child-theme.

**Comment by rdellwebworks** [comment]
Rocco unable to reproduce so Closing
