### ISSUE TITLE
FW0014 (Feature) Slider images on main page for scheduled posts

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#490]
https://wordpress.org/support/topic/slider-images-on-main-page-for-scheduled-posts

**Comment by Nikeo** [comment]
good point.
This should be fixed.
There would be a way by listening to the post status change with : 'transition_post_status'

Good post about it here : 
http://wordpress.stackexchange.com/questions/121160/publish-post-hook-isnt-working-for-scheduled-posts

=> I've never used this hook before : 'transition_post_status', It might be fired by WP in contexts that could create unwanted side effects. To handle with care.

**Comment by eri-trabiccolo** [comment]
Ah means that a scheduled post when become published isn't added to the slider?
Well the other workaround is to just enter the customizer which will erase the transient.
But yeah should be fixed.

**Comment by Nikeo** [comment]
your workaround would require a user action ? or I did not get it ?

**Comment by eri-trabiccolo** [comment]
Yeah sorry, I was talking about the workaround proposed by the user in the wp-org topic :)
