### ISSUE TITLE
FW0017 (Feature) Permanent Sticky Header for Mobile

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#492]
https://wordpress.org/support/topic/permanent-sticky-header-for-mobile

Would be a useful option in core.

**Comment by eri-trabiccolo** [comment]
I remember I did something for an user a long ago, I found it.

This is a good starting point:
https://gist.github.com/eri-trabiccolo/eb3454ddb5adbebaa72e
(except for the fact that gist decided to put 8 tabs as indentation, despite what I selected!!! :D) 

It' possible porting this in the core (or make an official snippet?), but we need to keep things simple. a) So something like : "Display a minimal header in mobiles" with a note which says that it will reflect exactly the same aspect of the sticky header, this means that all the options selected for the sticky will be taken in account (what to display, shrink or not the title/logo etc.)
The fact is that users might want this "min header" in mobiles but not the sticky header, so telling them:
"Enable the sticky header, so some options will be shown, select what you want, then turn it off.."
It's a mess.
b) Or we could force a behavior by default and give some snippet to further customize it dunno.
c) Or .. the opposite of a) we can make the "sticky header section" a "mini header section" and add a notice which says "The sticky header will reflect the option selected below". Here we have the "problem" that these options are current `tc_sticky_*` which we should change for consistency (hence a "migration" code is needed)
d) As the customizer now is really really faster we can consider to duplicate the sticky options for the mini header, keeping the two sets unrelated.

Last thought .. we have to define a mobile:
a) any mobile ( `wp_is_mobile()` ) despite the window's width?
b) any device but with the window's width as discriminant ?
c) both a) and b)

**Comment by Nikeo** [comment]
@eri-trabiccolo yes the customizer is faster so, I'm ok to duplicate the setting in two "chapters" : desktops and mobile.
Now what is a mobile ?
wp_is_mobile is not accurate enough since it does not take into account the tablet orientation ( portrait, landscape).
I guess this would require two steps 
1) server side : listen to wp_is_mobile to write some additional css and js
2) browser side if wp_is_mobile has returned true: display the mobile user defined sticky header but switch to desktop user defined sticky header for the tablet landscape case.

**Comment by eri-trabiccolo** [comment]
Not sure about 2) too
'cause the main problem in mobiles and the sticky header is the height more than the width.
User who wants this feature looks for a smaller header in terms of height.
And tablets height (unless they've a device pixel ratio > 1 ) is pretty small.
