### ISSUE TITLE
FW0018 (Issue) Feature "Load images on scroll" doesn't work in blogs

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#493]
https://wordpress.org/support/topic/feature-load-images-on-scroll-doesnt-work-in-blogs

**Comment by eri-trabiccolo** [comment]
Not sure what it was...
most likely we fixed it (probably here: https://github.com/presscustomizr/customizr/commit/58ba2f5c04c04a84e49d46de418771aab61afb6e)
Anyway I cannot reproduce the issue on the user's site.
fabioabba says:
>i have pages of galleries of pictures and there it works, but in single posts not..
>post: http://www.icefotolog.it/niagara-falls-buffalo-toronto/
>gallery: http://www.icefotolog.it/foto-week-32/

but  I can see it working in the both provided links.

**Comment by rdellconsulting** [comment]
Have asked for User update

**Comment by rdellwebworks** [comment]
User @eddy6 reporting still an Issue

**Comment by eri-trabiccolo** [comment]
I see, might depend on some other conflicting plugin.. maybe jetpack's photon.
Have to look into that.

**Comment by rdellwebworks** [comment]
I've asked for him to test after disabling Photon. Have just read this review: http://robincornett.com/jetpack-photon/ which I plan to refer to in future posts (unless there's a better one around?)

**Comment by rdellwebworks** [comment]
We can close. It was Jetpack/Photon.

**Comment by eri-trabiccolo** [comment]
Hello Dave I re-open this as photon is vastly used and we want to support jetpack's module as much as we can.
Will push a PR to fix this issue.

Thanks for reporting it!

**Comment by rdellwebworks** [comment]
I did respond to one with ‘we always have problems’ which did strike me as our problem. So glad you’re fixing it.

 

Still waiting for a win :(

**Comment by eri-trabiccolo** [comment]
Yeah compatibility issue aren't necessary fault of someone, if both respect the wp rules.
In this case photon was not compatible with a customizr feature as well as customizr feature wasn't compatible with photon. Jetpack is very popular and we can make "patches" for it, but Customizr is popular too so also plugins could make the same..
:D 

p.s.
yes I saw the draw.. :(
