### ISSUE TITLE
FW0019 (Doc) using Customizr category filter on pages that are not Front Page

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#494]
https://wordpress.org/support/topic/using-customizr-category-filter-on-pages-that-are-not-front-page

Menaka flagged as doc-candidate

**Comment by eri-trabiccolo** [comment]
Mmm, not sure we can do anything for it.
Anyway might be possible in the future when we'll complete the dev to allow users to create alternate/grid list wherever with shortcodes.

Not even sure a doc-candidate should be among the github issues.
@Nikeo do you want them here?

**Comment by Nikeo** [comment]
the theme is not ready for that now.
