### ISSUE TITLE
Potential issue with buddypress + WP4.4

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#495]
As reported by a user and apparenty only occurs with the Customizr theme

> Hello Nicolas, please help me we used your theme customizr for site with buddypress but problem disappear buttoms profile private message and the public https://buddypress.org/support/topic/problem-disappear-buttoms-profile-private-message-and-the-public/

**Comment by eri-trabiccolo** [comment]
Mmm, 
not able to reproduce it :| here.
Will look more into it.
User's website?

**Comment by Nikeo** [comment]
ok.
I've asked the user's url.

**Comment by eri-trabiccolo** [comment]
For what I understand that "button bar" is reloaded via ajax when the action requested is completed.
So there might be an issue in the response... let's see.

**Comment by Nikeo** [comment]
OK. I've also asked the user to disable all plugins but buddypress to see if it still occurs

**Comment by eri-trabiccolo** [comment]
:)

**Comment by eri-trabiccolo** [comment]
After logging in as admin to the user's website I've been able to reproduce the same issue with twentyfifteen theme.
So I'm inclined to exclude Customizr as culprit, as:
1) it happens with a standard theme too
2) it doesn't happen on my local install
3) it doesn't happen on our test install
(Customizr 3.4.16/wp 4.4/ buddypress 2.4.3)

**Comment by Nikeo** [comment]
ok let's close this
