### ISSUE TITLE
Wrong documentation link on Widget Placeholder

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#502]
Hi,

With reference to this thread on helpscout.
https://secure.helpscout.net/conversation/159499973/6563/?folderId=631714

Customer found the link on widget placeholder is wrong.
Please see screenshot http://i.imgur.com/h7f7xDs.png
The link is as follows, which leads to 404.
http://docs.presscustomizr.com/customizr/content-options#pages-and-posts-layout

Should be as follows.
http://docs.presscustomizr.com/article/107-customizr-theme-options-pages-and-posts-layout

Thank you.

Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel.

**Comment by denzelchia** [comment]
You are welcome! :)

**Comment by Nikeo** [comment]
good catch thanks Denzel :)
