### ISSUE TITLE
Site info error in admin

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#508]
As reported by a user

# IS MULTISITE :            No

# THEME | VERSION :         customizr | v3.4.16# WP VERSION :              4.4.1
# PERMALINK STRUCTURE :     /kontakt

# ACTIVE PLUGINS :
Call Now Button: 0.1.3
Custom Facebook Feed: 2.3.10
EU Cookie Law: 2.8.5
Google Analytics by Yoast: 5.4.6
Hello Dolly: 1.6
Page Builder by SiteOrigin: 2.2.2
Shortcodes Ultimate: 4.9.9
SiteOrigin Widgets Bundle: 1.5.4
Ultimate Addons for SiteOrigin: 2.3.0
WP Maintenance Mode: 2.0.3
WP Multibyte Patch: 2.5
Yoast SEO: 3.0.7

PHP Version:              7.0.1
MySQL Version:            <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function mysql_get_server_info() in /var/www/traneweb.dk/public_html/wp-content/themes/customizr/inc/admin/class-fire-admin_page.php:351
Stack trace:
#0 /var/www/traneweb.dk/public_html/wp-includes/plugin.php(525): TC_admin_page->tc_config_infos('')
#1 /var/www/traneweb.dk/public_html/wp-content/themes/customizr/inc/admin/class-fire-admin_page.php(224): do_action('__after_welcome...')
#2 /var/www/traneweb.dk/public_html/wp-includes/plugin.php(525): TC_admin_page->tc_welcome_panel('')
#3 /var/www/traneweb.dk/public_html/wp-admin/admin.php(236): do_action('appearance_page...')
#4 /var/www/traneweb.dk/public_html/wp-admin/themes.php(10): require_once('/var/www/tranew...')
#5 {main}
  thrown in <b>/var/www/traneweb.dk/public_html/wp-content/themes/customizr/inc/admin/class-fire-admin_page.php</b> on line <b>351</b><br />

**Comment by eri-trabiccolo** [comment]
http://php.net/manual/en/function.mysql-get-server-info.php
So maybe the user has php7 ?
Ok, we'll try the mysqli extension (let's just do a check on the existence of the function `mysql_get_server_info` instead of the check on the php version).

**Comment by eri-trabiccolo** [comment]
https://core.trac.wordpress.org/ticket/27703#comment:7
&&
https://core.trac.wordpress.org/ticket/27703#comment:8

So I'll use that .. Let me know if you think it's fine (tested here, with 5.6.15 which uses mysqli) 'cause we should port it to the plugins system-info too.
(PR coming)

**Comment by Nikeo** [comment]
What is 5.6.15, the version of what ?
thanks

**Comment by Nikeo** [comment]
OK php http://php.net/releases/5_6_15.php

**Comment by eri-trabiccolo** [comment]
sorry PHP 5.6.15
yes

**Comment by Nikeo** [comment]
5.6.15 is pretty recent. As a rule of thumb (not for this specific case), it would be more comfortable to test with previous versions

**Comment by Nikeo** [comment]
more safe

**Comment by eri-trabiccolo** [comment]
Yeah I have to build up a test environment for other stuff.

**Comment by Nikeo** [comment]
yep, this will be an important first thing to do once in Nice

**Comment by eri-trabiccolo** [comment]
Yeah... but as you can see in this case we had a problem with very new PHP versions, luckily it happened on a backend page.

**Comment by Nikeo** [comment]
out of topic, but we need to talk about a PHP7 test environment @eri-trabiccolo !

**Comment by eri-trabiccolo** [comment]
In 2 minutes 😛

Il 05/set/2016 08:40 AM, "Nicolas Guillaume (@nikeo on wp.org)" <
notifications@github.com> ha scritto:
