### ISSUE TITLE
WPGlobus issue, multilingual?

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#509]
Originally fixed in 3.4.14 but language issue?

https://wordpress.org/support/topic/wpglobus-and-customizr

**Comment by eri-trabiccolo** [comment]
Thanks Dave.
Don't think it's theme related honestly.
I'm not able to reproduce it here.
Will keep this open till we'll get an user's feedback.

**Comment by eri-trabiccolo** [comment]
User confirmed was a permalink issue not theme related then.
Closing this ;)
