### ISSUE TITLE
Post Metas Buttons: Hierarchical Taxonomy not correctly identified since wp 4.2

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#511]
As @menakas and @rdellwebworks reported Customizr, when printing post metas buttons, doesn't recognize the hierarchical tax.
@menakas discovered the culprit line -> https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-post_metas.php#L360

As @menakas has corectly pointed out, the `category_parent` property isn't a [Term](https://developer.wordpress.org/reference/classes/wp_term/) object field.

Though that check has always worked till wp 4.2, as far as I remember ('cause I can remember the category button with a dark grey color). *read the following comment with my analysis about the reason why it stopped working*

@menakas suggested to make a more proper check for that purpose:
`if (strcmp($term->taxonomy,"category"))`

Which is a good solution, though I think that we should extend it to all the hierarchical tax (even custom) so I think this would be more appropriate:
`if ( is_taxonomy_hierarchical($term -> taxonomy ) )`

p.s.
anyway, for a matter of consistency, we should change the CSS class from `btn-tag` to `btn-hier` or something of the sort, as it is used for hierarchical tax, and tags are not hierarchical :D !
But I already know this simple change would raise a lot of complains :)

**Comment by eri-trabiccolo** [comment]
Following my analysis about the reason, this is just to satisfy my curiosity, but can be useful for all those who have my same disease :D :
Took me a while to understand why it worked fine before and now it doesn't anymore.
The reason lies on something which looks totally unrelated.
That's the thing.
As @menaka said the `category_parent` isn't a Term object field, though we could use it anyways back in the past. That's 'cause category terms were (and still are in other contexts) filled with some (including the aforementioned one) specific fields, for backward compatibility: https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/category.php#L332

When are these fields added?
If you look at the interesting functions we use to retrieve the terms like [get_the_terms](https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/category-template.php#L1144) or [wp_get_object_terms](https://core.trac.wordpress.org/browser/tags/4.4/src/wp-includes/taxonomy.php#L2283) you see it is not called. But you can see that `get_the_terms` uses, when available, cached terms.
Here's the thing, there was something which cached the category term with the additional fields aforementioned in wp < 4.2 but not in wp >= 4.2, before we get the terms to build up the metas. And this 'something', in our case, is:
`get_the_categories`
which **was** called by `get_post_class`.
We use `get_post_class` [to fill the article selectors](https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-utils.php#L597).
[See the interesting diff](https://github.com/WordPress/WordPress/commit/04216633b2fc6e21a458481af3bd0abf036e59a3#diff-4dfc90c149824dd4effcc0724490f52dL451) in wp core.

To prove I'm not wrong (maybe :P) just add `get_the_category` before [this line] (https://github.com/presscustomizr/customizr/blob/master/inc/class-fire-utils.php#L597) in the customizr code and see that the category button has the `btn-tag` CSS class.

**Comment by giorgioriccardi** [comment]
I lost you towards the end, but congrats for the thoroughly analysis of the issue, impressive!

**Comment by eri-trabiccolo** [comment]
ahah thanks Giorgio.
Let me know which is the part not clear so I can amend it ;)

**Comment by menakas** [comment]
Awesome analysis Ricco! That's a lot of info for me to follow and discover. Thanks :-)

**Comment by eri-trabiccolo** [comment]
Thanks Menaka, glad it helps ;)

**Comment by Nikeo** [comment]
great analysis Rocco. My code was relying on a cached property, made by a function called before actually building up the metas. Let's say I've been lucky it workied till now.
Thanks :)

**Comment by eri-trabiccolo** [comment]
:) Thanks (gotta go now)
