### ISSUE TITLE
Woocommerce Product Layout in Mobile

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#515]
Hi,

With reference to this thread on helpscout.
https://secure.helpscout.net/conversation/162421906/7247/?folderId=607546

Woocommerce recent update changed the product layout in mobile.
It's showing all 4 columns in mobile.
I have provided a css solution to customer, not a perfect solution but it works for customer.

I am thinking maybe we can provide some solution in our theme to make the product layout back to 2 column again.

Thank you.
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
I'm inclined to think it's a woocommerce issue.
They fixed it here -> https://github.com/woothemes/woocommerce/commit/5481820668b05737fa361c3e4af076007611d4cc

**Comment by denzelchia** [comment]
Hi Rocco,

Thank you for this information.

Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Hello Denzel,
latest woocommerce changelog says:
Fix - Fix responsive product sizes when the columns class is missing.

So looks like they fixed it ;)

**Comment by denzelchia** [comment]
Thank you for informing me. :)
