### ISSUE TITLE
Single posts featured image

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#517]
Enabling the option in Appearance -> Customize -> Content: home, posts, ... -> Single posts 
we display either the featured image (post thumbnail) or the first attachment (consistently with what Customizr does with fp and post lists thumbnails), but there's no mention of the latter in the option's notice.

Also, is it right?
I mean, if the post doesn't have a thumbnail but it has at least an attachment, you might see (if the attachment is still in the content), the image twice:
1) before the content
2) within the content

Maybe yes, in this case we should provide a better notice for that option.

**Comment by Nikeo** [comment]
I agree. Open to your suggestion !

**Comment by eri-trabiccolo** [comment]
My idea is to show there only the actual thumbnail, but I see this can cause an issue for users used to see there also an attachment. That's the tricky point, do we want to do this "switch" and handle the complaints?
If not a notice should be added. In this case, see also -> https://github.com/presscustomizr/customizr/issues/518
that doc should be upgraded talking about what we consider as featured image..

**Comment by eri-trabiccolo** [comment]
What if we add a new option, disabled by default for old users, enabled by default for new users which says:
"Display only the actual post thumbnail if available"

With a notice with a link to how to set the featured image doc which will contain what *we* mean for featured image?

I think is a good compromise (always considering how fast the customizer is now)

**Comment by Nikeo** [comment]
I'm with you

**Comment by eri-trabiccolo** [comment]
Compromises :D
