### ISSUE TITLE
Featured Page : add a doc link in the customizer explaining how to display an image

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#518]

**Comment by eri-trabiccolo** [comment]
We should also say that not only the post thumbnail is taken in account but also the first attachment if the post thumbnail is not available.

**Comment by eri-trabiccolo** [comment]
The better thing is to upgrade the doc specifying the attachments thing there.

**Comment by Nikeo** [comment]
customizer notice + doc upgrade would be perfect

**Comment by eri-trabiccolo** [comment]
Ok I can upgrade the doc in my impeccable English, then you'll correct it :P

**Comment by Nikeo** [comment]
let's do so

**Comment by Nikeo** [comment]
:dancers:
