### ISSUE TITLE
Header : Fix mobile alignment issue between icons menu button

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#519]
![2016-01-22_14-48-12](https://cloud.githubusercontent.com/assets/3038156/12512259/7e5cb1d6-c117-11e5-93c4-ee96beaf9651.png)

**Comment by eri-trabiccolo** [comment]
Mmm, we can raise the cart icon a little bit, but the socials misalignment isn't that evident in the demo.
Might be due to a custom font-size/line-height configuration...
