### ISSUE TITLE
Slider link with QTranslate X in pre-path mode

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#531]
https://wordpress.org/support/topic/slider-link-with-qtranslate-x-in-pre-path-mode
justinbb says:

> In class-content-slider.php, function tc_get_single_slide_model(), determination of $link_url, there is a problem which becomes evident when using QTranslate X in pre-path mode (i.e., language code inserted into the URL path).
> 
> The intention is that if slide_custom_link_key is not found by get_post_meta, a fallback method should be used to obtain the link: get_permalink($link_id). My site depends on this behavior.
> 
> The problem is that apply_filters is being called on the result of get_post_meta before checking whether it is null. When QTranslate X is active, apply_filters will end up calling QTranslate X's language-based rewriting; in particular, a null input will produce a non-null output. This causes Customizr's test for null to fail, and therefore the fallback not to be executed. The result is a slider button that points to the site's home page instead of to the desired page.
> 
> The following patch will correct the problem. This problem is not new (I've been patching it on every update ever since switching to QTranslate X).

```
--- class-content-slider.php orig       2016-01-27 21:13:48.000000000 -0500
+++ class-content-slider.php    2016-01-27 21:25:55.000000000 -0500
@@ -109,10 +109,12 @@
     //link post id
     $link_id                = apply_filters( 'tc_slide_link_id', esc_attr(get_post_meta( $id, $key = 'slide_link_key' , $single = true )), $id, $slider_name_id );
     //link
-    $link_url               = apply_filters( 'tc_slide_link_url', esc_url(get_post_meta( $id, $key = 'slide_custom_link_key', $single = true )), $id, $slider_name_id );
+    $link_url               = esc_url(get_post_meta( $id, $key = 'slide_custom_link_key', $single = true ));

     if ( ! $link_url )
       $link_url = $link_id ? get_permalink( $link_id ) : $link_url;
+    else
+      $link_url = apply_filters( 'tc_slide_link_url', $link_url, $id, $slider_name_id );

     //link target
     $link_target_bool       = esc_attr(get_post_meta( $id, $key= 'slide_link_target_key', $single = true ));
```

**Comment by eri-trabiccolo** [comment]
The patch provided by Justin fixes the issue. and basically the PR I'll propose will use his code, with just one variant, the following line:
```$link_url = apply_filters( 'tc_slide_link_url', $link_url, $id, $slider_name_id );```
will not be part of an else statement.
Even if is correct that qtranslateX doesn't parse an external url (hence the else statement justin proposes) that filter can be used for different purposes and I think it should not be conditioned.

**Comment by justinbb** [comment]
Thank you!
I agree with taking the call to apply_filters() out of the else; I did it that way only to make my change as minimal as possible, since I am not familiar with the code as a whole. It does indeed make better sense to call apply_filters() unconditionally.

**Comment by eri-trabiccolo** [comment]
Yeah, I think your solution was perfect for your purpose.
Thanks for raising and solving this issue :D
