### ISSUE TITLE
3.4.17 and Firefox images not displayed

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#534]
https://wordpress.org/support/topic/3417-and-firefox-images-not-displayed
https://wordpress.org/support/topic/urgent-lightbox-thumbs-are-missing-after-update

The problem resides here -> https://github.com/presscustomizr/customizr/blob/master/inc/assets/js/parts/jqueryimgSmartLoad.js#L145
that statement while "valid" for chrome, isn't for firefox, and maybe ie, for checking whether or not "something" is undefined.
They need:
`type of undefined !== type of something`
or
` 'undefined' !== type of something`

Plus:
looks like firefox can take a while to actually load the image (with an srcset). Meaning that, that img.load callback is fired even if the actual image isn't loaded yet, hence `$_img.originalHeight();`(Width) returns 1px (the dummy image height/width)..

So this issue is a combination at least of 2 specific browsers behavior.
For example I wasn't able to see it on the demo site (gallery page), 'cause there the gallery images do not have srcset attribute.
Of course this issue doesn't happen only with the gallery images, but as we do not have specific responsive thumbnails yet, there is pretty much the only place you would see the srcset attribute :)

Another consideration:
latest jetpack version seems to not remove the img width/height anymore from the images (hence no data-recalc related issue -> https://github.com/presscustomizr/customizr/pull/500).
Hence that whole js (+ small php) compat code wouldn't be needed anymore, though photon still has the php/js code (even if not effective as far as I can see). Probably it will be re-added, or probably not, let's see how things go before completely remove it.

**Comment by Nikeo** [comment]
ok merged. this .attr() method is a trap
