### ISSUE TITLE
Attachment Details : Create  a direct link to the slider metabox

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#537]
The idea is to make it simpler for the new users to find the way to add a given image to a slider.

Currently a user has to 
1. go in the media library
2. then click on an image
3. then click on _Edit more details_
4. Then scroll down to the slider meta box

In the future, it would be better to have a direct link _Add this image to a slider_, before _Edit more details_ 

=> there must be a way to filter this content in wp core

This link would direct the user right to the slider meta box in the attachment edit page.

![add_to_slider0](https://cloud.githubusercontent.com/assets/3038156/12695017/856cf65a-c740-11e5-90fa-e5612af6159b.png)

This link would direct the user right to the slider meta box in the attachment edit page.

![add_to_slider1](https://cloud.githubusercontent.com/assets/3038156/12695018/87b9b222-c740-11e5-8c98-6911f211f1ef.png)

**Comment by eri-trabiccolo** [comment]
Makes sense :D, will look at it

**Comment by Nikeo** [comment]
ok cool!

but don't forget the priority stuff : font awesome, please focus on it exclusively until it's done :)

**Comment by eri-trabiccolo** [comment]
Sure, don't worry ;)
