### ISSUE TITLE
Customizer number control : wrong id

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#539]
Why : 
`id="posts_per_page"`

here : https://github.com/presscustomizr/customizr/blob/dev/inc/admin/class-tc-controls-settings.php#L160

to fix but check if there's any regression ?

**Comment by eri-trabiccolo** [comment]
Mmm,
who knows why. :D
Looks like it has always been so.. (or at least I couldn't find when it became so in the github history).
Anyway the input id attribute for the customizer isn't taken in account (cannot see any other setting having an id), we can get rid of it (after some tests).

p.s.
Just ended the FontAwesome mapping. :P

**Comment by Nikeo** [comment]
yeah !
