### ISSUE TITLE
Outline in firefox appears around all links

### ISSUE THREAD

**Issue by Maxxxos** [presscustomizr/customizr#543]
Hi Nikeo.
First of all thank you for really good theme.

Today I found that arround all links when clicked in firefox (44.0) appear border. This red border.
![image](https://cloud.githubusercontent.com/assets/13926774/12801397/20443baa-cae5-11e5-9922-628d1aa49a7c.png)

I newby in webdevelopment so I not sure but look that it is not must be such way and only in firefox.
This hapens arround all links on any page (menu, image link, in sidebar, logo)

I found that it is from a:focus

in red.css row 54

`a:focus {
  outline: thin dotted #333;
  outline: 5px auto #f93c3c;
  outline-offset: -2px;
}`

And I repair it for my (after one hour serching) adding 
in child css next
`a:focus{
outline:0;
}`

or in tc-common.css add this here row 83
`a:hover,
a:active {
  outline: 0;
}`

So, I not sure that it is bug but looks strange.

Thank you

**Comment by Nikeo** [comment]
Hi Maxxos, yes the new version of Firefox handles the outline differently.
It's not really a bug but it looks really ugly I agree.
I'll work on a fix for this;

Thanks for reporting :)

**Comment by Maxxxos** [comment]
Thank you
