### ISSUE TITLE
Scroll bar blocking settings in RTL

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#555]
Hi,

Please refer to this helpscout issue.
https://secure.helpscout.net/conversation/168833001/8711/?folderId=631714

Customer reported that when using Chrome on Windows 10 PC, with view port size 1280X675
The scroll bar is blocking the settings.
Please see screenshot provided by customer.
http://i.imgur.com/dA59SxU.png

Currently I do not have a Windows PC to replicate this issue.

I am only able to prove that this issue does not exist on Mac
Chrome browser. http://i.imgur.com/n2thu6s.jpg
Safari browser. http://i.imgur.com/tmjbW2q.jpg
Firefox browser. http://i.imgur.com/uneDTHL.jpg

Please help.

Thank you,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
I see they're not completely blocked, they're still accessible .. am I wrong?
We'll try to fix it in the next theme release.
For the moment rtl users having this issue might want to add the following code to their child-theme functions.php:
```
add_action('customize_controls_print_styles', 'fix_rtl_controls');
function fix_rtl_controls(){
?>   
  <style id="fix-rtl-control">.customize-control { float: none; }</style> 
<?php      
}
```

Thanks.
Rocco

**Comment by dotanshema** [comment]
Thank you, it solved the problem :)
By the way, did you see the message I sent to you in connection with the translation?
You do not have translation project in wordpress.org, that's why I asked you send me the updated files.
But I of course I prefer that the project for Hebrew translation will be open in wordpress.org.

**Comment by eri-trabiccolo** [comment]
Hello dotanshema,
glad you solved the controls issue.

About the translation issue, we're looking at it.
We'll keep you posted ;)
Thanks again!

**Comment by denzelchia** [comment]
Hi Rocco,

Thank you for the code snippet.

Regards,
Denzel

**Comment by JTS-IL** [comment]
It fixes the issue but the standard in RTL sites is to move the scroll bar to the right.
How can it be done?

**Comment by eri-trabiccolo** [comment]
@denzelchia ;)
@JTS-IL not sure how, that's the standard  behavior in the customizer (with any theme) - so it's a wp "issue".
Maybe something like this will work:
`.wp-full-overlay-sidebar-content * {
    direction: rtl;
}
.wp-full-overlay-sidebar-content,
ul[class*=accordion] {
    direction: ltr;
}`
not sure...
