### ISSUE TITLE
Add a link to doc in the customizer

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#560]
When clicking on the interrogation point the contextual helped is revealed.
![link_to_doc](https://cloud.githubusercontent.com/assets/3038156/13046794/492cb87c-d3db-11e5-8437-f997dc800ea9.png)

The idea would be to always append a link to the doc here.
Php filter if possible or javascript

**Comment by eri-trabiccolo** [comment]
Do not think is possible with php, I cannot see available filters, at least for the "first info" (I mean the one shown above). Have to see for the others.
Would be great having contextual doc links..

**Comment by andrewfandrew** [comment]
Hi, I came across http://justintadlock.com/archives/2011/06/02/adding-contextual-help-to-plugin-and-theme-admin-pages which might be a way to do it using PHP filter.

**Comment by andrewfandrew** [comment]
Hi, I have found the relevant core file. The code that controls the text displayed is at the bottom:
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-customize-panel.php

**Comment by eri-trabiccolo** [comment]
Yeah.
That's for the panels though, cannot really use php filter on the "first info" (as I said above, and I meant the info shown as soon as you enter the Customizer, the one displayed in the picture above
https://core.trac.wordpress.org/browser/trunk/src/wp-admin/customize.php#L140
)
Anyway I'm on it, js for the "first info" and panel/section description for panels and section ;).
Let's see if the boss likes it :P

**Comment by andrewfandrew** [comment]
Hi, sorry you were correct: it is a JS not a PHP filter task.

**Comment by eri-trabiccolo** [comment]
Yeah Andrew,
if you're interested you can try the pr above.
p.s.
to actually see a difference in the "first info" you have to run grunt in order to build the back js.
The panel info is, instead, visible since it's only php, in the info block of the Global Settings panel.

**Comment by andrewfandrew** [comment]
Thanks Rocco, That is a useful pointer to use grunt. I have read your code and it is useful seeing how to implement these solutions.

**Comment by andrewfandrew** [comment]
Hi, I have not used travis but just signed up and linked my github account to travis. Rocco I see your code did not pass the travis unit test? I would like to assist. Or if you could explain a little about how you are using travis? Can you give any tips on tracking down issues raised by travis tests?

**Comment by eri-trabiccolo** [comment]
Hi Andrew,
well the thing is that the Travis environment doesn't have php 5.2 installed (while the config of this repo on Travis seems to require it) and it fails to install it, see:
https://travis-ci.org/presscustomizr/customizr/jobs/109402435

Removing this https://github.com/presscustomizr/customizr/blob/master/.travis.yml#L20
then should be fine.

Not a big deal ;)

**Comment by andrewfandrew** [comment]
Thanks Rocco. Got that.
Can you please advise on workflow if i want to make pull requests to core? I have forked the repo to my github then cloned the forked version to my local dev box. It seems i should pull from upstream every so often to keep my local repo synced with the master repo (Nikeo's version)?

If i had written some code to fix #561 would i checkout a new branch on my local repo test it there and then make a pull request to Nikeo? And would i have needed to run 'grunt build' on my local box to test out the JS? I have been building a few JS apps on my local box and i have tools such as grunt and node.js configured on it.

**Comment by eri-trabiccolo** [comment]
Hello Andrew,
you should keep your repo updated, especially the dev branch.
That's the branch against to you should make your pull requests.
Nikeo's repo doesn't really exists anymore, has been moved to the organization's one.
So the branch I'm talking about is:
https://github.com/presscustomizr/customizr/tree/dev

And yes grunt should be ran to test js/css stuff. But still the PR should be pushed only with the modified sources, not with the file generated by grunt.
For example, changing the CSS will require acting on the less files, you should test your changes running grunt to generate the actual css files, but the PR should not contain the css generated files, only the ".less", that's 'cause otherwise will be too hard understanding the diffs. :D

You can find the available grunt tasks here -> https://github.com/presscustomizr/customizr/blob/dev/gruntfile.js#L30
(I, also, suggest you to remove this line in your gruntfile.js:
https://github.com/presscustomizr/customizr/blob/dev/gruntfile.js#L29
(and remember to ignore that file in gitignore ;))
)

So that should be the workflow to submit the PR, then submit it and wait ... Nicolas is the only one merger :D 

Hope this helps ;)

**Comment by andrewfandrew** [comment]
Thanks Rocco that answer really does help! Now i know how to get set up.

**Comment by eri-trabiccolo** [comment]
Glad it helped :D

**Comment by andrewfandrew** [comment]
Hello Rocco, I have just cloned your customizr-doc-link-BETA branch to my local machine and tried it out but not seen the link appear. Have you tried out your code?

**Comment by andrewfandrew** [comment]
Hi, I have just cloned your BETA branch to my local machine and tested it out but not seeing the link generated, so far. Have run 'npm install' then 'grunt prod_dev' and 'grunt prod_dev_js' but not worked.

**Comment by eri-trabiccolo** [comment]
Hi, well yeah I tried it, but I will try it out again.
The doc link in the "first" info depends on grunt + a refresh of the customizer js (wp uses to cache it). You should be able to see the doc link in the Global settings panel without these problems though.
I'll check again

**Comment by andrewfandrew** [comment]
Okay, thanks. I may not have done the right grunt command or just not cleared the cache properly. Let me know how it goes, thanks, A

**Comment by eri-trabiccolo** [comment]
Hello andrew, I tested the branch again and it works here. Bye

**Comment by andrewfandrew** [comment]
Hi Rocco,
Thank you for that. I have just figured it out my end. I needed to run a
different grunt task and it looks perfect!

Cheers, Andrew

**Comment by eri-trabiccolo** [comment]
:)
