### ISSUE TITLE
Yelp icon showing up instead of Linkedin icon

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#565]
Hi,

A customer reported this issue on helpscout.
https://secure.helpscout.net/conversation/171817937/9291/?folderId=631714

I am able to replicate it.
In Appearance -> Customize -> Global settings -> Social Links
At the input for Linkedin, You can see that the icon is Yelp not Linkedin
I added the following URL https://www.linkedin.com/uas/login
Screenshot http://i.imgur.com/idEOcxO.jpg

On the front end, show up a Yelp icon.
Screenshot http://i.imgur.com/mgGNWSu.jpg

I think we should keep Linkedin and also provide Yelp.

Thank you.

**Comment by eri-trabiccolo** [comment]
Thanks Denzel.
I think something happened while building customizr-pro (merged a wrong version).
The dev Customizr branch works fine.
@Nikeo ?
