### ISSUE TITLE
Website: 3-bar menu not working

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#567]
Menu is not working on http://presscustomizr.com/ front page

**Comment by Nikeo** [comment]
Hi Dave, how can I replicate the problem ?
Screenshot possible ? 
Thanks :)

**Comment by rdellwebworks** [comment]
![pc menu](https://cloud.githubusercontent.com/assets/11431088/13169959/cf7f2d80-d6e0-11e5-87d7-55bfe169b9ce.PNG)
Click on 3-bar and nothing happens

**Comment by Nikeo** [comment]
all browsers ?

**Comment by Nikeo** [comment]
only on front page ?

**Comment by rdellwebworks** [comment]
Just checked and problem is with FF (Developer)

**Comment by Nikeo** [comment]
ok.

As a rule of thumb, for issues related to presscustomizr.com, please rather report them by email instead of using the customizr github repo.

Or maybe this issue has been reported in the forum ?

**Comment by rdellwebworks** [comment]
No, I've noticed it for a few days. Will use email next time.

**Comment by andrewfandrew** [comment]
Hi Nicolas, I hope to make a few pull requests in the near future, just getting to grips with the structure of your theme which i have been using for a few years. But you could create a separate repo for your documentation site here on github. Would introduce too much extra admin?..

**Comment by Nikeo** [comment]
@andrewfandrew doc in github is not scheduled right now. We'll see if it can help in the future maybe ?

**Comment by andrewfandrew** [comment]
@Nikeo Ok, sounds good. Rocco gave me some valuable info on how to develop the theme locally e.g. how to use grunt and not committing the compiled css but rather the changed LESS files. That gives me a head start. But I have an idea for my first pull request, which is really a test to 'dip my toes in the water..' There is a typo in the comments of files which i could search and replace. I know this is trivial and will hardly affect the theme.. The word 'instantiate' is spelt as 'instanciate'.  I can do a search and replace through files and folders using SED? Then i can make a pull request? 

If that works i can do more useful things as i understand the code better?..

**Comment by rdellwebworks** [comment]
This problem seems to occur on Front Page.

Forum User site: http://www.myhauntlife.com/

Not working in FF or Chrome

**Comment by eri-trabiccolo** [comment]
Thanks Dave,
I think it depends on W3TC... mm
works fine in the demo and in my local installs..

**Comment by rdellconsulting** [comment]
Seems to be working in latest FF Developer so can close this.

**Comment by Nikeo** [comment]
ok
