### ISSUE TITLE
Autogenerated post slider : include scheduled posts

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#569]
As reported by a user 

> Hi there,
> First off, love the theme and think it's great.
> 
> However, I have noticed that when I schedule a post, when my item posts, it never updates the front page slider that is autogenerated based off my latest posts.
> 
> The workaround is to go into the post and update it, but that sort of defeats the purpose of scheduling a post.

https://wordpress.org/support/topic/slider-images-on-main-page-for-scheduled-posts?replies=2

**Comment by eri-trabiccolo** [comment]
see #490

**Comment by Nikeo** [comment]
oh yes
