### ISSUE TITLE
Browser-level navigation gestures not working with Customizr

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#575]
As reported by a user
> I've noticed this with all of my Customizr installs - browser navigation by trackpad gesture appears to be disabled on sites using Customizr (even your own).

> I've tested in Safari, Chrome and Firefox - navigation gestures are disabled on all three.

> So much of my day-to-day workflow involves being able to swipe forward and back in the browser for regular navigation, and it consistently throws me for a loop when I get to a Customizr-based site (mine or others) and I can no longer use gestures that are built into the browser functionality.

> Is this something that can be fixed / worked around / re-enabled?

> I love so much about Customizr, but this is one aspect that I struggle with, and would love it if there was a fix for it.

> Again, this isn't about any particular function / feature of the theme - simply that it appears to disable the browser-level navigation gestures (two finger swipe left and right to go forward and back).

> Any help would be most appreciated.

**Comment by eri-trabiccolo** [comment]
As Denzel confirmed, this is due to the page smoothscroll.
The proposed PR might fix is, though disabling the feature when trying to scroll with a touchpad - now default behavior in the latest original script version.
