### ISSUE TITLE
Add a centered menu option (for regular horizontal menu)

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#576]
**In Customize > Header > Navigation Menu**
Currently if the user chooses the horizontal menu, he/she can select between left or right aligned in the _Menu position_ setting

The idea would be to add a third "Centered option" to this setting.

**Comment by eri-trabiccolo** [comment]
I have a sketch of snippet for this purpose:
https://gist.github.com/eri-trabiccolo/999ac7969818b0997439
What to do when sticky header?

**Comment by Nikeo** [comment]
sticky header => If not too complicated, let's maintain the menu centered when sticky

**Comment by eri-trabiccolo** [comment]
Well, no it's not.
That's what it does right now.. but I don't know how much sense might it have...

**Comment by rdellconsulting** [comment]
This would be High on my Wishlist. I've dabbled with Flexbox which seems a good solution. Is Flexbox something you've considered for next generation Czr?

**Comment by Nikeo** [comment]
why not but I'm not familiar with it, so I'll need to study it a little bit.
The other, thing that could delay its implementation is the browser support issue for IE
http://caniuse.com/#feat=flexbox
I'm sure there are some library lile modernizr which can help for that, but this needs to be adressed
