### ISSUE TITLE
Move WooCommerce header options in header > Design and layout

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#577]
only if woocommerce enabled of course

**Comment by eri-trabiccolo** [comment]
So I gave a better look to this.
Here's the thing (which I think we discussed on asfjksajdflkana when started implementing the woocommerce header cart option):
our compatibility codes are fired at `after_setup_theme` with priority 30.
When customizing this is fine, we can filter the theme settings map adding the new options, they will be rendered and well handled.
But, when in front, we set up the "cached" options at after_setup_theme with priority 10 => https://github.com/eri-trabiccolo/customizr/blob/master/inc/class-fire-utils.php#L31
This means that if we add these new options directly in the plugin compatibility code we'll not have them available in the "defaults" (clearly I'm talking about the case when defaults are not set in the db, hence for new installs).
Of course this is not a big deal as we'll have no error, the only thing is that, for new installs, these options, whatever is their default value, will be treated as `false`.
Hope I've been understandable.
So we can:

- do the opposite, add them to the map and then remove them (so they're are not rendered in the customizer) if nothing prevents us to do that (meaning using a filter which the compat code will hook to prevent the removal - just setting a bool )-> convoluted but maybe better
- don't care about the default value, and sleep tight with the idea that the cart will not be rendered by default
- think about a small "api" which will allow us to update the defaults on demand
- leave everything as is now

let me know ;)

**Comment by Nikeo** [comment]
OK.
adding them to the main setting map (instead of the plugin compat) with an active_callback argument could do the trick. What do you think?
More about the active_callback argument here : https://make.wordpress.org/core/2014/07/08/customizer-improvements-in-4-0/

**Comment by eri-trabiccolo** [comment]
Yeah I remember that callback but is available since 4.0
