### ISSUE TITLE
Sub menu block with long label get cut off on the right hand side of the screen.

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#583]
Hi,

With reference to the following thread on helpscout.
https://secure.helpscout.net/conversation/177095805/10334/?folderId=631714#thread-461026796

Customer reported that sub menu block with long label get cut off on the right hand side of the screen.
Please see screenshot. http://i.imgur.com/KKbPQ59.jpg
Website URL http://www.vectracom.fr/en/

I am able to replicate this issue on my localhost
Please see screenshot of my menu setup.
http://i.imgur.com/Dz3ZYG1.png
For this test, I have named a menu item label -> Level 02 - This is a long long label
As long as there is a long menu label in a sub menu block, it will get cut off on the right hand side of the screen.
Please see screenshot. http://i.imgur.com/I2V3J7F.jpg

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel for reporting this.
The fix wouldn't be simple.
At the moment the only thing to do is to place the main menu item far from the window's edge.
So .. say after Home
anyway I'll look at how to fix this.

**Comment by denzelchia** [comment]
Hi Rocco,
Understand. :)
Thank you.Denzel



    _____________________________

**Comment by eri-trabiccolo** [comment]
:D 
Thanks Denzel ;)

**Comment by eri-trabiccolo** [comment]
Hello Denzel,
the issue should be partially fixed with the proposed PR.
Let me know if you think otherwise ;)
Byez..

**Comment by denzelchia** [comment]
Hi Rocco,

I do not know how to test your fix.
I will wait for the next theme update.

Thank you.

**Comment by eri-trabiccolo** [comment]
Hello Denzel,
thanks.
Have a nice day
