### ISSUE TITLE
Need to update help links in Customizr Pro Theme WordPress admin help page

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#585]
Hi,

When clicking the Help button on WordPress admin toolbar, it will load the following URL ../wp-admin/themes.php?page=welcome.php&help=true
Screenshot. http://i.imgur.com/po4ZXUr.png

The button -> "Get support in the forum" leads to http://presscustomizr.com/support-forums/forum/customizr-pro/ which is closed.
I think we should update the link to point to http://presscustomizr.com/support/

The button -> "Read the documentation" leads to http://presscustomizr.com/customizr/
Maybe we can update it to link to the following URL, which I think is more relevant.
http://docs.presscustomizr.com/article/182-getting-started-with-the-customizr-pro-wordpress-theme

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks for this Denzel.
Let's wait for the boss thoughts ;)

**Comment by Nikeo** [comment]
This has been updated.
Thanks for this very useful feedback Denzel !

**Comment by denzelchia** [comment]
You are welcome!
Thank you. :)
