### ISSUE TITLE
Woocommerce cart icon not update ( live ) with number of items added to cart

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#588]
Hi,

This is reported by a customer on helpscout.
https://secure.helpscout.net/conversation/179844082/10760/?folderId=631714

Using our demo site shop page as an example.
http://demo.presscustomizr.com/shop/
Clear your browser history, so as to clear any item in shopping cart.

When you click on an item's Add to cart button.
The cart icon on header does not show the item count.

It only shows up after you reload the webpage or navigate to another page.
Please see screenshot for explanation. http://i.imgur.com/PZ8GB43.png

Not sure if this is a bug or a possible enhancement.

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
yes it doesn't react to the ajax add-to-cart (when you don't have that option enabled the page reloads by default). It should!

**Comment by denzelchia** [comment]
Thank you! :)

**Comment by eri-trabiccolo** [comment]
implemented in dev
