### ISSUE TITLE
Dropdown to viewport singular issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#593]
https://secure.helpscout.net/conversation/185640242/11710/?folderId=607546

Very very singular.
jQuery(window).height()

fails... mah.
It could be a conflicting plugin, but cannot understand why, it's against the jQuery api docs.

Anyway, at the same time, looks like - at least with a live test - that using the javascript way:
`window.innerHeight` doesn't produce the issue.

Do you think would be safer switch to it?
I think so...

**Comment by Nikeo** [comment]
yes clearly.
the only side effect is that `window.innerHeight` is not supported by ie8.
We might add a simple check on `typeof  window.innerHeight === 'undefined'` could be added to fallback on $(window).height().

**Comment by eri-trabiccolo** [comment]
Ok, I do that
