### ISSUE TITLE
WooCommerce : the color variation is not visible on a product page

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#601]
> on my page and on your demo page under http://demo.presscustomizr.com/product/ship-your-idea-2/
the variation "Color" is in a white font. It´s difficult to read. How can i change the color?

![2016-04-19_08-25-52](https://cloud.githubusercontent.com/assets/3038156/14629686/aeef3c48-0608-11e6-8605-8ac150d77ba2.png)

**Comment by eri-trabiccolo** [comment]
Adding something like this in the CSS will be fine.
The alignment is still pretty messy..
```
.woocommerce .variations .label {
    color: inherit;
}
.woocommerce div.product form.cart .variations td, .woocommerce div.product form.cart .variations th { background: none;vertical-align: super;}

```

**Comment by Nikeo** [comment]
why don't you push a PR? 

ah ah ah ah ah ah

**Comment by geryg** [comment]
Hi Nicolas,

thank you your help. It works. Im new in wordpress. What do you mean 
with "why don't you push a PR"?

Greets Gernot

Am 19.04.2016 um 12:46 schrieb Nicolas Guillaume (@nikeo on wp.org):

**Comment by eri-trabiccolo** [comment]
Hello geryg,
he was referring to me, don't worry ;)

**Comment by geryg** [comment]
Ok, thank you too for your help...

Am 19.04.2016 um 13:06 schrieb Rocco Aliberti:

**Comment by eri-trabiccolo** [comment]
You're welcome

**Comment by geryg** [comment]
I have one more problem with the breadcrumbs in woo commerce in association with customizr. With the original woo theme storefront the breadcrumbs works fine. But with customizr the breadcrumbs from the categorys, undercategorys and products are wrong.

Is it possible to use the original storefront settings for my shop.

Thank you in advance for your help...

Gery
