### ISSUE TITLE
WooCommerce : breadcrumb issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#603]
> I have one more problem with the breadcrumbs in woo commerce in association with customizr. With the original woo theme "storefront" the breadcrumbs works fine. But with customizr the breadcrumbs from the categorys, undercategorys and products are wrong.
> 
> Is it possible to use the original storefront settings for my shop.

**Comment by geryg** [comment]
Its a great support here and customizr is awesome theme. For me as a wordpress beginner im very thankfull for the help here.

**Comment by geryg** [comment]
Does nobody have an answer for me?

**Comment by eri-trabiccolo** [comment]
Hello geryg,
the support for the free theme is provided on the wordpress.org support forum:
https://wordpress.org/support/theme/customizr

Anyway you can use something like the code below (in your child-theme functions.php)
https://gist.github.com/eri-trabiccolo/bea4c56e7ef7b1622bfa47065b10fd87

to achieve that.

Hope this helps.

**Comment by geryg** [comment]
He Rocco, thank you very much. The breadcrumb issue is fixed.
But now the footer in woo commerce is faulty.

www.hundelust.de/shop

**Comment by eri-trabiccolo** [comment]
Sorry, problem of unbalanced tags.
In the code I gave you, replace:
` $defaults['wrap_after'] = '</div></div></div>';`
with
` $defaults['wrap_after'] = '</div></div></div></div>';`

**Comment by geryg** [comment]
Thank you. Now everything's fine, problem solved!!!

**Comment by eri-trabiccolo** [comment]
glad to hear that ;)
