### ISSUE TITLE
Enable shortcodes in text widgets by default ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#615]
add_filter('widget_text', 'do_shortcode');

side effects ?

**Comment by eri-trabiccolo** [comment]
Not that I know, a lot of plugins and themes (which have shortcodes), of course for their own purposes, do that. My only "concern" is.. why this is not by default in wp? It sure introduce some additional computation when rendering a widget but..
So what we can safely do is to add a new option (in advanced settings maybe) to enable it (disabled by default). IMHO
What do you think?
