### ISSUE TITLE
customizer : wrong display behaviour when previewing the theme?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#616]
I have in my wordpress themes 7.
If you select a different theme Customizr, and I "see preview" of Customizr (without activating) the menus you see complete, as img.02
If active Customizr as the theme of the site, the first menu in the customization right disappear. View from img.01.
So, yes it's a problem when customizing the theme activated as default.
It is not clear, i do a video to load on my Google+

![img 01](https://cloud.githubusercontent.com/assets/3038156/15170943/d351866a-174a-11e6-903b-3f51150d623e.jpg)

![img 02](https://cloud.githubusercontent.com/assets/3038156/15170946/d65ab2dc-174a-11e6-8768-9e6e29b706e2.jpg)

**Comment by eri-trabiccolo** [comment]
Which wp version? Cannot see the dev preview switcher..
