### ISSUE TITLE
Remove complete translations on wp.org

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#619]

**Comment by eri-trabiccolo** [comment]
see https://github.com/presscustomizr/customizr/pull/617

**Comment by eri-trabiccolo** [comment]
bump

**Comment by JTS-IL** [comment]
Is there an easy way to upload the currant Hebrew translation to wp.org?

**Comment by eri-trabiccolo** [comment]
Not at all @JTS .
Neither theme/plugin authors can do that.
The only way is to request a PTE status on polyglots for each locale.
https://make.wordpress.org/polyglots/tag/editor-requests/
Then depends on the locale team whether or not the request will be accepted, you might pass a "test" with your locale polyglot's team.
Are you interested in that? If yes let @nikeo know so he can ask the PTE status for you in .. which locale? he_IL right? That's the only thing the author can do is that.  :/

**Comment by JTS-IL** [comment]
Grrrr....
I've been translating the earlier versions of Customizr for few months, and now every thing is going to be flushed away?
I am very intrested in tranforming my work to wp.org, so if @nikeo can make the needed connections - I'll do what is needed.
BTW - he_IL - right (double meaning :-) )

**Comment by eri-trabiccolo** [comment]
;)

**Comment by Nikeo** [comment]
Hi @JTS-IL !
I've had the same feeling a few weeks ago when I reaized that my french translations had not been loaded in the translation system... :(

Except for this frustration feeling at the beginning, I've discover that the new translation workflow proposed by WordPress is actually really good.

The way it works in a few words.
Each language is managed by a team. Each language team translates the "projects" on WP.org . A project can be a theme, a plugin or WP core.

There are of course several level of capabilities in each team.
Anyone having an account can become a contributor for one or several projects and language team.
A contribution is a single string translated for a project.
The person who can upload the translation file (instead of translating each strings one by one) for a given project is called the PTE.
I've become the PTE for my language for both the Customizr theme and the Hueman theme.

Each language team setup its own rules to assigne roles and capabilities. The common pattern is that a PTE of a given project for a given language has to be a native speaker of the language.

I would love to propose you as PTE for Customizr, this way you'd be able to load the Hebrew .po file on this page https://translate.wordpress.org/projects/wp-themes/customizr/he/default (the upload field will be displayed as soon as you'll become a PTE).

If you're OK, I'll ask the Hebrew translation team to promote you as PTE for Customizr.
I'll need your WordPress.org user name for that.
Let me know what you think about this ?

**Comment by JTS-IL** [comment]
I will be happy to be the Hebrew PTE for Customizr!
my wp user is JTS_IL :-)

**Comment by Nikeo** [comment]
Great!
I just contacted the Hebrew Polyglot team on the Translate WP blog (this is the way to do it)
https://make.wordpress.org/polyglots/2016/06/10/customizr-theme-pte-request-for-hebrew/
I'll keep you updated if they need to contact you.

Have a good day

**Comment by Nikeo** [comment]
Hi @JTS-IL , you've been added as PTE
https://make.wordpress.org/polyglots/2016/06/10/customizr-theme-pte-request-for-hebrew/

Let me know if you need any help to upload your translation .po file here : https://translate.wordpress.org/projects/wp-themes/customizr/he/default
