### ISSUE TITLE
Compatibilty with Super Socializer Plugin

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#623]
Hi,

Please refer to this thread for the details.
https://secure.helpscout.net/conversation/222458367/15393/?folderId=631714

Customer is having issue getting Super Socializer plugin's share icons to show up on Frontpage.
This is the plugin https://wordpress.org/plugins/super-socializer/

Customer does not accept the custom code that I had provided and request a compatibility fix to be included in Customizr Pro Theme.

Thank you.

**Comment by denzelchia** [comment]
Hi,

Customer feedback that this issue is related to featured pages.
It works, if featured pages is not enabled on homepage.

https://secure.helpscout.net/conversation/249487252/17421/?folderId=631714

Thank you

**Comment by eri-trabiccolo** [comment]
Thanks Denzel.
On it.

It pertains to FPU right? Not to the featured pages embedded in the Customizr theme, can you confirm?

**Comment by denzelchia** [comment]
Hi Rocco,

Yes, it's for FPU in Customizr Pro.
Thank you for the snippet. 
https://gist.github.com/eri-trabiccolo/24a792b787e5cd40f197e7f1c749051c

I had informed customer, that it will be available in next theme update.

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
I close this then, will leave it open on fpu ;)

Best Regards,
Rocco
