### ISSUE TITLE
Featured page image : Line beside image for iphone6s and iphone 6

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#632]
As reported on the forum : https://wordpress.org/support/topic/bug-customizr-line-beside-featured-images?replies=2#post-8780585
## Screenshots

![__iphone_6](https://cloud.githubusercontent.com/assets/3038156/18080174/9b5a851c-6e94-11e6-8959-e589a136e1a3.jpg)
![iphone_6s](https://cloud.githubusercontent.com/assets/3038156/18080175/9d016412-6e94-11e6-863a-e6dee8b215d6.png)
## Original forum thread

>  don't want to necro an old thread so here's my own go. I have some news here. Maybe together we 
> 
> can fix this.
> 
> Many people have noted a problem on mobile devices with the Customizr theme where a vertical line is displayed to the left of the "featured images". It looks like a bad crop job on the part of CSS or the like. Only thing is, everyone just says "phone" or "mobile" but never addresses the DEVICE they're using. I'm here to correct this (because it's annoying the hell out of me).
> 
> I noted the same problem on my site with my personal phone, an iPhone 6+. I've checked with handful of Android devices and none are affected. Here's the breakdown from my testing.
> 
> Affected
> iPhone 6S+
> iPhone 6+
> 
> Unaffected
> iPhone 6
> iPhone 6S
> (iPhone 4/5 series not yet tested. Will test this week)
> Samsung Galaxy S4
> Samsung Galaxy S5
> Samsung Galaxy S6
> Samsung Galaxy Note 5
> Samsung Galaxy Note 6
> Samsung Galaxy Tab 3
> Samsung Galaxy Tab 4
> 
> Common Denominators for affected devices
> Screen resolution of 1080p/1080x1920
> iOS version 9.3.4
> 
> Tech links for the screens and functions: https://www.paintcodeapp.com/news/iphone-6-screens-demystified
> 
> Pretty sure it's something to do with how the iPhone 6S+/6+ renders images on the screen in 1080p. Something in Customizr is throwing it off.
> 
> So... if you are affected... what is your device, OS version, browser, etc. Let's get to the bottom of this.
> 
> Thanks guys,

John

http://www.adelphisecurity.com

**Comment by eri-trabiccolo** [comment]
See also #474

**Comment by jmullentech** [comment]
As stated in my follow up post in the OP, apparently the Kindle Fire HD (2nd Gen, 7", firmware v7.5.1, Android 4.0.3 ICS) is another device also affected. This really has me scratching my head. If there's anything I can do for you guys, feel free to reach out.
