### ISSUE TITLE
No caption for light box images ? (except for galleries)

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#634]
As reported

>  Image Galleries work great but whenever I link to an image directly in a post or non gallery page, the image shows in a Light box ok but there is no caption. How do I add a caption feature?

**Comment by eri-trabiccolo** [comment]
It depends on the way we call the lightbox and our post processing, let's call it this way. Basically we use the image title or it alt attribute only:
https://github.com/presscustomizr/customizr/blob/master/inc/assets/js/parts/_main_jquery_plugins.part.js#L104

I remember @ElectricFeet worked on this long time ago and proposed a patch/enhancement.
I can try to find and port it to the current theme's version.
