### ISSUE TITLE
Compatibility issue with Magee shortcodes plugin due to bootstrap

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#640]
When Magee shortcodes plugin is installed and activated, it produces conflict. Display of featured page images is affected.
Conflict seems to arise from **bootstrap.css v3.3.4** enqueued by the plugin

**Comment by eri-trabiccolo** [comment]
Hello @menaka,
thanks for reporting this.
Can you test if adding the following custom CSS solves the issue?
`/* should fix also the alternate post list layout when displaying rounded thumb*/
.round-div,.marketing {
   -webkit-box-sizing: content-box;
   -moz-box-sizing: content-box;
   box-sizing: content-box;
}
`

Bests

**Comment by menakas** [comment]
Thanks @eri-trabiccolo 
It solves the issue.

**Comment by eri-trabiccolo** [comment]
Thanks for the feedback @menakas !!!

**Comment by brightkitten** [comment]
There is still a compatibility issue with the the sidebar widgets displaying at the bottom of the page when the Magee Shortcodes Plugin is activated.
