### ISSUE TITLE
Compatibility issue- menu missing - with Magee shortcodes plugin

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#642]
When Magee shortcodes plugin is installed, the menu goes missing.
Issue reported at forums here:
[https://wordpress.org/support/topic/customizr-theme-and-magee-shortcodes-plugin/#post-8211897](https://wordpress.org/support/topic/customizr-theme-and-magee-shortcodes-plugin/#post-8211897)

Verified to be true on local installation. A conflict between bootstrap versions included by theme and plugin.

**Comment by eri-trabiccolo** [comment]
Hello @menakas 
unfortunately the fact that that plugin uses a different bootstrap (css but mostly js) version leads to several compatibility issues... Will try to see what we can do to address and hopefully solve (I'm doubtful about that though) them all.

Thanks!

**Comment by brightkitten** [comment]
Has there been any updates on this issue? I installed Customizr yesterday - LOVE it - but there is sa compatibility issue with the the sidebar widgets displaying at the bottom of the page when the Magee Shortcodes Plugin is activated.

**Comment by eri-trabiccolo** [comment]
Hi @brightkitten ,
try adding the following to your custom CSS as a temporary workdaround:
`[id^=customizr-slider].container, .container[role="main"] {
    padding: 0;
}
@media (max-width: 767px) {
  .row.column-content-wrapper {
    margin-right: 0;
  }
}
`
We'll work on a more comprehensive compatibility fix for this.
