### ISSUE TITLE
Theme update issue/Compatibility issue - Revolution slider plugin

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#646]
On update of theme, sliders disappeared.
Reported in this post in the support forums.
[https://wordpress.org/support/topic/sliders-disappeared-with-3-4-23/#post-8253388](https://wordpress.org/support/topic/sliders-disappeared-with-3-4-23/#post-8253388)

**Comment by eri-trabiccolo** [comment]
Hello @menakas ,
not able to reproduce these 2 issues too :(
a) If "our" slider disappeared there might have been a db corruption (specific for our theme options :().
b) revslider : cannot reproduce that too (but not tested with latest revslider), might be a js related issue with the inline script used to activate the parallax, which should not be printed where there is no slider. Though say you have both a revslider and our slider, that issue will still occurr :/
