### ISSUE TITLE
Theme update issue - Unable to use Custom Taxonomy in menus

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#647]
As reported in this issue in support forums.
[https://wordpress.org/support/topic/custom-taxonomies-cant-be-used-in-menus-suddenly/](https://wordpress.org/support/topic/custom-taxonomies-cant-be-used-in-menus-suddenly/)
After theme update, the user is not able to add Product Category menu links

**Comment by eri-trabiccolo** [comment]
So the user reports that the whole "Product Categories" menu item types, as well as other custom taxonomies, are not available here:
![wc-pc](https://cloud.githubusercontent.com/assets/7689242/19107077/cc3faab4-8aea-11e6-9926-e7b6c016360c.png)
right?

I'm not able to reproduce that.
Also we don't have any specific code for the backend menu, neither we made changes in the latest release to justify this issue.

Might be a theme unrelated issue, several plugins conflicting among them, and/or something that has to do with the server configuration (max_input_vars/max_post_vars).
