### ISSUE TITLE
Footer-amoforms plugin causes wp admin bar issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#658]
Reported on helpscout and wp.org by the same user
https://wordpress.org/support/topic/footer-amoforms-wp-admin-bar-problem/

> i have version 3.4.33 and when choose default layout (right sidebar)---> my footer and wp admin bar are disappeared, and contact forms don't operate...
> 
> when i choose full width layout everything ok...
> 
> i updated to v 3.4.33 in my second website and my footer is still disappeared.. my amoforms( contact forms) doesn't operate and my wp admin bar doesn't appear. i deleted the theme from server and then i installed it again from wp,i have the same problem… 
> 
> maybe within this installation there is conflict between customizr theme and amoForms.

**Comment by eri-trabiccolo** [comment]
I don't know this plugin.. Is it a premium one?
(also: cannot find the helpscout topic :()

**Comment by Nikeo** [comment]
I don't think that you'll find more infos in the helpscout topic. All reported informations by the user (not pro) are there.
You can use the wp.org forum topic to ask more informations https://wordpress.org/support/topic/footer-amoforms-wp-admin-bar-problem/

this is the one : https://fr.wordpress.org/plugins/amoforms/
I don't know it as well, looks pretty popular

**Comment by eri-trabiccolo** [comment]
Thanks,
cannot reproduce it at the moment :/
