### ISSUE TITLE
Slider problem ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#659]
Reported

> hello, i try to change title text at my picture, which i include in slider, i need only picture without text, but i cant do it, please, help me
> 
> i can't change the text title and comment forms to empty values, it is automatically
> filled to the previous value. I need to reload image and clean this forms at once to get only picture.

**Comment by Nikeo** [comment]
@eri-trabiccolo can you please check when you'll have time ?
Can it be related to the prefix changes ?
Thanks

**Comment by eri-trabiccolo** [comment]
Couldn't reproduce this :/
