### ISSUE TITLE
Enhancement: Can slider behave different when resolution changes?

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#661]
As per this comment thread [http://presscustomizr.com/customizr-v3-4-23-introduces-parallax-scrolling-for-the-sliders/#comment-2957989881](http://presscustomizr.com/customizr-v3-4-23-introduces-parallax-scrolling-for-the-sliders/#comment-2957989881), the user believes that the slider's behaviour in high resolution monitors is not desirable.

A very subjective issue, though. 

Bringing it up so that the other options can be considered, if not already done.

**Comment by eri-trabiccolo** [comment]
Hello @menakas 
thanks for reporting this.
As you replied it has to do with the slides centering and not with the parallax.
Though that's an option (as well as the parallax) that can be disabled. In that case, most likely, depending on the viewport, the slides cut off will occur on the bottom.
