### ISSUE TITLE
Side Menu ( Vertical ) bug -- affects Customizr Pro Theme only

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#667]
Hi,

Customer reported this bug on helpscout.
https://secure.helpscout.net/conversation/268978528/18704/?folderId=631714

The Side Menu ( Vertical ) when activated, has extra spacing and is not fully expanded.
Please see my screen-cast.
http://screencast-o-matic.com/watch/cD6teQjmxL

Thank you for your kind attention.

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks a lot Denzel,
I move this issue in the pro repo!
We're working on a fix!

Best Regards,
Rocco
