### ISSUE TITLE
Missing German Language file in Theme ( Customizr Pro Theme )

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#668]
Hi,

This is an issue for Customizr Pro Theme.
Customer reported that German Language files are missing in recent updates.
https://secure.helpscout.net/conversation/269544953/18733/?folderId=631714

Customer send us a gentle reminder, to remember to include de_DE.mo and de_DE.po  in the next Customizr Pro Theme update.

Thank you very much for your attention. :)

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel
we're working on a fix.

Best regards,
Rocco

**Comment by denzelchia** [comment]
Hi Rocco,

You are welcome!

Thank you. :)
