### ISSUE TITLE
[Snippet] Reposition Tagline

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#676]
According to this issue reported on the forum, snippet to be changed to be compataible with updated theme: [https://wordpress.org/support/topic/code-snippet-does-not-work/](https://wordpress.org/support/topic/code-snippet-does-not-work/)

**Comment by eri-trabiccolo** [comment]
Thanks @menakas .
Will change the snippets asap according to the latest theme prefixes changes.
