### ISSUE TITLE
[Enhancement] Snapchat social button

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#682]
As per this forum request, it would be good to have Snapchat social link in the default set.
[https://wordpress.org/support/topic/snapchat-social-button/#post-8431852](https://wordpress.org/support/topic/snapchat-social-button/#post-8431852)

Considering that snapchat is gaining in popularity, we may want to consider it.

**Comment by eri-trabiccolo** [comment]
Thanks for this @menakas.
Looks like the snapchat icons have been introduced in font-awesome 4.6
We're running the version 4.5.
We have to upgrade it, indeed.

Best regards.

**Comment by eri-trabiccolo** [comment]
A PR has been done, though we need to better test if the FontAwesome upgrade introduces any issues.

**Comment by menakas** [comment]
Do we have a suite of test cases?
What is the usual testing procedure before every release?

**Comment by eri-trabiccolo** [comment]
Hi,
we don't have a preset suite of test cases for that. We are working on improving the tests overall.
For this specific issue the test would be (and that's what we did) just display all the social icons plus articles/widgets/titles with format icon.
Thanks :)
