### ISSUE TITLE
AddThis conflict

### ISSUE THREAD

**Issue by TKList** [presscustomizr/customizr#687]
This theme always has issues with AddThis plugin.

**Comment by Nikeo** [comment]
Can you elaborate about the problems you're having ?
That would help thanks !

**Comment by TKList** [comment]
http://tklist.us Homepage AddThis does not work. No share buttons on excerpts, no recommendations. 
other pages it is hit and miss what shows and doesn't show. Sometimes nothing shows, sometimes buttons show but not recommendations and sometimes both work. This has been going on for about two years. I have reported this before, to you and AddThis, but the problems continue.

**Comment by TKList** [comment]
Note: it happens even when all other plugins are disabled.

**Comment by TKList** [comment]
Problem still exists after latest update: Customizr version 3.4.37

**Comment by Nikeo** [comment]
OK. I've assigned it to the next release milestone

**Comment by TKList** [comment]
Looks like the issue was with my configuration some how. I started another site with all the same plugins and it seem to be all working. My apologizes for wasting your time.
