### ISSUE TITLE
Menu button in the header displaying wrong when tags are on

### ISSUE THREAD

**Issue by trainslated** [presscustomizr/customizr#689]
Hello. I have a simple problem on my site that I am creting using your theme. When I set the menu layout in the header to the right as I would like it to be, and the logo to the left - the menu button is displayed in the centre.

The problem disappears when:
-I either turn on the social media links in the header to be displayed
-or I turn of displaying the tags

Unfortunately I don't want neither of those to happen.

Kind regards,
Jacob.

http://trainslated.com

**Comment by eri-trabiccolo** [comment]
Hello @trainslated,


You have different ways to avoid that, with a few lines of css
You can
1) move the button below the tagline by:
- stretching the tagline:
```
.navbar-wrapper .site-description {
    width: 100%;
}
```
or 
```
.tc-header .btn-toggle-nav {
    clear: right;
}
```
2) have tagline and the menu button on the same line moving tagline on the left:
```
.navbar-wrapper .navbar .site-description {
    float: left;
}
```
To apply custom CSS you might want to refer to [the theme's documentation](http://docs.presscustomizr.com/article/38-how-to-change-css-code-in-customizr)
Hope this helps.

For further problems would you mind opening a topic on the [wordpress.org forum](https://wordpress.org/support/theme/customizr)?
There it's where the team handles the support.

Best regards :D
