### ISSUE TITLE
Google Fonts / Need local fonts

### ISSUE THREAD

**Issue by KZkici** [presscustomizr/customizr#690]
Hello,

I'm using the theme for a local server, to be uploaded on the WWW in the near future.

However, it is causing a heck of a time trying to load pages due to google fonts (online) as the server does not have internet access.

Can you make an option for the theme to use local fonts instead? 

Please advise,

Thank you,

KZ.

**Comment by Nikeo** [comment]
Hi @KZkici, this option is not scheduled for the moment but there should be a way to download the fonts you need and use them in the theme with a filter.
http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server
