### ISSUE TITLE
Jetpack Gallery issue since v3.4.35

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#691]
> Since the last update to Version 3.4.35 the Jetpack Plugin does not work anymore and in my images gallery window the option of "tiles" where the pictures were all put together in one square or shown in circles next to each other, is gone. My blogposts look silly now... 
http://claudigivesitatri.de
what can I do? thanks!

**Comment by HiroshiSaeba** [comment]
I've sold a part of the problem.

With jetpack and in your gallery settings you must choose link image to nothing instead of file-media or page of join file.

**Comment by eri-trabiccolo** [comment]
hi @HiroshiSaeba 
sorry still not able to reproduce this issue whatever "link to" I choose :(
