### ISSUE TITLE
[Documentation] Hooks API

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#693]
In the [Hooks API page ](http://presscustomizr.com/customizr/hooks-api/)documenting the available hooks,
the file names to be updated to correspond to latest version.

Hook names to be updated for the following:
tc_show_post_list_excerpt -> tc_show_excerpt
tc_show_post_list_thumb -> tc_show_thumb

**Comment by Nikeo** [comment]
This part of the documentation has not been updated since a while unfortunately.
As the new version of Customizr theme will be released by early January 2017, the hooks api will have to be updated.
