### ISSUE TITLE
[Enhancement] Ability to turn on/off parallax scrolling on specific pages

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#695]
According to this request on the disqus forums, [http://presscustomizr.com/customizr-v3-4-23-introduces-parallax-scrolling-for-the-sliders/#comment-3032613494](http://presscustomizr.com/customizr-v3-4-23-introduces-parallax-scrolling-for-the-sliders/#comment-3032613494), the user wants to be able to turn on/off parallax scrolling on specific pages.

**Comment by Nikeo** [comment]
This will be possible with the customizer scope feature that will first be introduced in Hueman Addons plugin (as discussed with you on skype) and then in the Customizr Addons plugin.
