### ISSUE TITLE
Snippet Link redirects to Customizr pro page

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#699]
This link from the snippets page redirects to the Customizr Pro Page.
[http://presscustomizr.com/snippet/center-header-block-items/](http://presscustomizr.com/snippet/center-header-block-items/)

**Comment by eri-trabiccolo** [comment]
Hi @menakas ,
thanks for reporting this.
Looks like @nikeo fixed it.
Can you confirm?

Thanks

**Comment by menakas** [comment]
Hi @eri-trabiccolo,
@nikeo did solve the issue. But this one link still redirects to pro page. I checked it. Can you too check?

**Comment by eri-trabiccolo** [comment]
Yep, sorry, I did and worked fine.
Still "broken" for you?

**Comment by menakas** [comment]
Ah yes, resolved now.

**Comment by eri-trabiccolo** [comment]
Great, thanks for the feedback! ;)
[closing this then]

**Comment by menakas** [comment]
Hi @eri-trabiccolo,
See the redirection again this morning.

**Comment by eri-trabiccolo** [comment]
Thanks,
it works fine now form here, seems to be pretty random.
We'll see :D
