### ISSUE TITLE
BBPress => increase font-size

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#700]
> the font size with customizr on the bbpress forums is really small by default. A lot of my users said it was too small.
> Some themes offer a better design for bbpress and buddypress (ex: zerif lite). it's too bad.
> 
> It would be really great to improve the support for these plugins (these ones are the most used)

**Comment by eri-trabiccolo** [comment]
Sure we can improve this, but to be honest font-sizes are bbpress choices (in px not in em), we just don't interfere with those. :D
