### ISSUE TITLE
Mobile Menu issue after upgrade to WP 4.7

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#701]
As reported by a user on Twitter

> Customizr free theme has menu problem on mobile after WP 4.7 update. Menu opens then promptly closes to X & is inaccessible

**Comment by Nikeo** [comment]
@eri-trabiccolo would you mind habing a look to it ?
I'm asking the user to also report the bug on the free theme forum

**Comment by eri-trabiccolo** [comment]
Looks more like a plugin conflict (bootstrap v>2.x)

**Comment by eri-trabiccolo** [comment]
Cannot reproduce it on the test website, my previous guess still stands :/
