### ISSUE TITLE
WooCommerce image issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#712]
After update to Customizr Pro 1.2.36 ver i dont have img product in me woocommerce snop

**Comment by eri-trabiccolo** [comment]
cannot reproduce :/

**Comment by Nikeo** [comment]
me neither...

**Comment by ElectricFeet** [comment]
I had this in another theme where I had some functions.php code that removed the featured images from posts and pages. I hadn't realised that the woocommerce product pages fire `is_single()`. Resolved with `is_single() && (! is_product() )`. Could be this have been the cause?

I'd close this after a year without any more info.
