### ISSUE TITLE
WooCommerce bug on grouped product page

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#713]
> Hi,

I'm using Customizr Pro version 1.2.36. On this WooCommerce Grouped Product page, the product content is bleeding over into the right sidebar instead of wrapping in the center column:

https://rayoflightmassagetraining.com/product/three-rolmt-dvds-for-97/

How can I fix this to wrap the grouped product data properly?

Thanks in advance,

John

**Comment by eri-trabiccolo** [comment]
Mmm I didn't see this.
though the page isn't accessible anymore...

**Comment by Nikeo** [comment]
originally reported here : https://secure.helpscout.net/conversation/297688004/20545/?folderId=607546

**Comment by eri-trabiccolo** [comment]
Ah I see.
fixed...
