### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by eehmke** [presscustomizr/customizr#719]
Wordpress version 4.7
Customizr version 3.4.36
I upgraded my site to PHP 7.0. All went fine, the wordpress portal runs without any hickup. I installed then the plugin PHP Compatibility Checker:
https://de.wordpress.org/plugins/php-compatibility-checker/
it reports an error in line 190 of wp-content/themes/customizr/core/framework/class-controllers.php: break statement outside of loop. I think this is an error of the checker plugin, but it can be easily avoided by enclosing the statements in braces:
```
          // eehmke remove warning (break outside loop)
          foreach ( $this -> controllers as $group => $views_id ) {
            foreach( $controller_ids as $id ) {
              if ( in_array($id, $views_id) ) {
                $controller_cb = $id;
                $controller_group = $group;
                break 2;
              } //if
            } //foreach
          } //foreach
```
As long as the checker plugin is not updated, it would be nice if the customizr theme just did not trigger this error.

**Comment by eri-trabiccolo** [comment]
Thanks @eehmke 
fixed in dev
