### ISSUE TITLE
display secondary menu option is not available anymore 

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#720]
As reported

> I am using the Customizr theme free version, which I may upgrade.
> But in the navigation menu there is no option to display the secondary menu like you show it.
> 
> But there is an issue, under apperance > customize > header > navigation menu , there is no option to dipslay a second menu, no box to check like yu explain it.

**Comment by Nikeo** [comment]
@eri-trabiccolo could you please make a quick check on your side ?
I'm not able to replicate.

**Comment by eri-trabiccolo** [comment]
Not able to reproduce the bug neither.
Are we sure the user is using the side menu? Secondary is available only in that case.

**Comment by Nikeo** [comment]
OK.
I'm going to let him know this and tell him to follow up on the forum.
Thanks
