### ISSUE TITLE
Overlapping Menu / submenu / sub-submenu (2nd order)

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#726]
> Hi team!
> 
> Due to the very small margin-left between 1st submenu and the 2nd sub-submenu it is difficult to navigate.
> 
> http://delta-projekt.com/
> 
> In detail: If you choose "Consulting" and moving the mouse downwards, the submenu with "Management" and "Sales" switches directly to the sub-submenu of the first item "Management". To move to the sub-sub-menu of "Sales" you have to leave the sub-submenu with mouse-left-move, than downwards und then to the right.
> 
> Normally, you can move downwards and the sub-submenu appears only, if you choose one of the item.
> 
> To avoid this, you have to move on the very left side, but this is not user friendly.
> 
> For the interim time, please give me the code to adust the space between the sub-menu and the sub-submenu. If the sub-submenu is more one the right side, this problem is less.
> 
> Thank you very much!
> 
> Regards
> 
> Klaus

**Comment by Nikeo** [comment]
@eri-trabiccolo any idea ? 
This is not a frequent feedback but quite interesting I think in terms of user experience.
should we push the sub menu a little more on the right like on the upcoming v4 ?

**Comment by eri-trabiccolo** [comment]
Actually in v4 the submenus start from the right edge of their parent (left: 100%, or right with the upcoming snake). ;)
