### ISSUE TITLE
PHP 7.0 compatibility issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#727]
I have just tried to upgrade my website (http://sculptor.armrigconsulting.co.uk/), which uses the free customizr plugin, to PHP 7.0, but when I do all I get is a white screen. After reverting to PHP 5.6, I installed a PHP compatibility checker plugin and it produced the following result:
Customizr

Possibly not PHP 7.0 compatible.

FILE: /home/armrigco/public_html/sculptor/wp-content/themes/customizr/core/framework/class-controllers.php
-------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------
190 | ERROR | Using 'break' outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0
-------------------------------------------------------------------------------------------------------------------------

Since PHP 7 has been around for some time now and PHP 5.6 has just come out of its Active Support period, I'm surprised that Customizr is not compatible with it. Is there something I'm missing or doing wrong?

Thanks

Colin

**Comment by eri-trabiccolo** [comment]
see https://github.com/presscustomizr/customizr/issues/719
That is a fake issue raised by that plugin.
It's just that the break statement is in nested loops whose start and end aren't defined by braces.
This is totally legal in php (and not only) if each nested loop consists in only one line of code.

That file is not even required, as of now, by the theme ;). 
Furthermore in our test environment, running php7, requiring and actually using that file we have no issues of any sort.

I already changed that part in dev-c4 with the reason "more readability" :D which is the only actual reason I could stand :D

That's a plugin issue ;)

@nikeo 
if you want tomorrow we can merge the current dev-c4 to avoid other complains.
Even if it's not our fault, but I understand that it's not users fault either :D

**Comment by Nikeo** [comment]
@eri-trabiccolo OK. Yes that is legal. Maybe not a good practice for the compatibility checker ?
dont know.
Anyway, yes, let's merge the latest dev, fine for me.

**Comment by eri-trabiccolo** [comment]
https://wordpress.org/support/topic/vaultpress-false-positive/
