### ISSUE TITLE
Demo website WooComerce: cannot access the single products/product categories pages. Permalinks update needed?

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#729]
Example
http://demo.presscustomizr.com/produit/flying-ninja/

Permalinks issue?
Seems that the wp language is set to french while WooCommerce products permalinks still refers to the english base:
http://demo.presscustomizr.com/product/flying-ninja/

edit:
same thing for product categories:
http://demo.presscustomizr.com/categorie-produit/posters/

**Comment by Nikeo** [comment]
yep that was a permalink issue.
Thanks, you rock !

**Comment by giorgioriccardi** [comment]
Though there are still few French labelled items:
![image](https://cloud.githubusercontent.com/assets/3901192/21902981/de45d7b8-d8b2-11e6-90f2-20ed8e39b76b.png)
and the &copy; is still 2015 ;-)

**Comment by eri-trabiccolo** [comment]
thanks @giorgioriccardi for this.
I think you're right, probably will be better to back on english :D 
Also the 2015 should be updated.

@nikeo , your opinion?

**Comment by Nikeo** [comment]
@eri-trabiccolo @giorgioriccardi yes 100% agree !
Fixed.
Thanks for reporting this
