### ISSUE TITLE
Slider : clicking arrows doesn't work

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#737]
> We are using the customizr theme with a slideshow on the Home page.
> 
> The three slides appear and rotate through, however when I place my mouse near the left or right edge of the images and click on the
> arrows, then nothing happens. I was expecting that clicking the arrow would advance me to the next or previous slide but it doesn't.

> # SITE_URL: http://clark-collective.com
> # HOME_URL: http://clark-collective.com
> # IS MULTISITE : No
> 
> # THEME | VERSION : customizr | v3.4.37# WP VERSION : 4.7.1
> # PERMALINK STRUCTURE : /%postname%/
> 
> # ACTIVE PLUGINS :
> Akismet: 3.2
> amr shortcode any widget: 3.3
> Contact Widgets: 1.4.0
> Custom Post Widget: 2.9.2
> Huge IT Responsive Slider: 2.3.6
> Limit Login Attempts: 1.7.1
> Logos to replace Page Titles: October 21, 2016
> Ninja Forms: 3.0.24
> Optima Express IDX Plugin: 3.7.1
> RSS Just Better: 1.4
> WP-ShowHide: 1.04
> 
> PHP Version: 5.4.45
> MySQL Version:
> Web Server Info: Apache/2.4.23
> 
> WordPress Memory Limit: 40MB
> PHP Memory Limit: 256M
> PHP Upload Max Size: 32M
> PHP Post Max Size: 48M
> PHP Upload Max Filesize: 32M
> PHP Time Limit: 120
> PHP Max Input Vars: 1000
> PHP Arg Separator: &
> PHP Allow URL File Open: Yes
> WP_DEBUG: Disabled
> 
> Show On Front: page
> Page On Front: Home (#155)
> Page For Posts: Blog (#328)
>

**Comment by eri-trabiccolo** [comment]
Optima Express IDX Plugin: 3.7.1 contains bootstrap 3
that is most likely the reason.

Another side effect is the abrupt slid.

Dunno what we can do about this honestly, maybe we can act on bootstrap js/css and change our prefixes to avoid conflicts..?!

**Comment by Nikeo** [comment]
OK.
Let's keep this in mind for the future updates ( we knew it already).
Can you reply to the user on helpscout ( assigned to you ) and let him know about this potential conflict ? (tell him to follow up on the wp.org forum )
thx

**Comment by eri-trabiccolo** [comment]
I reopen this as we still have some slider compat issues with several bootstrap plugins.
https://secure.helpscout.net/conversation/319867959/23394/?folderId=607546
