### ISSUE TITLE
Slider messy when manually changing slides

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#746]
https://wordpress.org/support/topic/slider-messy-when-manually-changing-slides/
> Hi there!
> 
> After updating to Customizr free v3.4.36 i started to get issues with the slider, specifically when manually changing slides.
> 
> I made a video to better understand whats wrong. I have 3 slides and if i wait so they automatically slide it works fine, but when i use the arrows to manually change them, it gets messy as you can see on the video.
> 
> I removed the slider and created it again but the issue remains.
> 
> Here is the video link: http://www.filipecosta.com/downloads/customizr-slider-issues.wmv

**Comment by Nikeo** [comment]
system informations requested to the user

**Comment by eri-trabiccolo** [comment]
Actually without looking at the website I cannot understand what's going on.
Maybe he comes from a very old version and has something in the child-theme (which I think he uses as he has the search among the menu items) which conflicts.

**Comment by Nikeo** [comment]
The user has provided more details.

> Hi and thanks for answering!
> 
> 1. I’m not currently using any cache plugin nor i believe server cache
> 2. Are you sure it’s related with some plugin? I have disabled some that maybe related to pictures and the ones i remember were last activated, but i still have issues. I will try to disable one at a time, but it would be hard, since i have a lot of enabled plugins!
> 
> I made a new video, and as you can see, the behavior is different from the first one when the slider it automatically changing pictures. Sometimes it gets like this: http://www.filipecosta.com/downloads/customizr-slider-issues1.wmv
> 
> Here is my appearance > about Customizr:
> 
> # SITE_URL: http://www.filipecosta.com
> # HOME_URL: http://www.filipecosta.com
> # IS MULTISITE : No
> 
> # THEME | VERSION : customizr | v3.4.37# WP VERSION : 4.7.1
> # PERMALINK STRUCTURE : /%category%/%postname%-%post_id%/
> 
> # ACTIVE PLUGINS :
> Admin Branding: 1.1.2
> Advanced AJAX Product Filters for WooCommerce: 1.1.6
> AfterShip – WooCommerce Tracking: 1.6.6
> Akismet: 3.2
> All In One WP Security: 4.2.5
> Cookie Notice: 1.2.37
> Custom Product Tabs for WooCommerce: 1.5.2
> Download Manager: 2.9.4
> Google Captcha (reCAPTCHA) by BestWebSoft: 1.27
> Jetpack by WordPress.com: 4.5
> Loco Translate: 2.0.11
> Moloni: 1.0
> Multibanco (IfthenPay gateway) for WooCommerce: 1.8.8.2
> Perfect WooCommerce Brands: 1.4.3
> Portugal States (Distritos) for WooCommerce: 1.5.1
> Redirection: 2.5
> TinyMCE Advanced: 4.4.3
> UpdraftPlus – Backup/Restore: 1.12.30
> WC – APG NIF/CIF/NIE Field: 1.0.1.1
> WooCommerce: 2.6.13
> WooCommerce – APG Weight and Postcode/State/Country Shipping: 2.0.2.5
> WooCommerce Colors: 1.0.6
> WooCommerce Extra Product Sorting Options: 2.5.0
> WooCommerce Grid / List toggle: 1.1.0
> WooCommerce Pay for Payment: 1.3.8
> WooCommerce Product Archive Customiser: 1.0.4
> WooCommerce Product Details Customiser: 0.2.0
> WooCommerce Product FAQs: 3.0.3
> WooCommerce WooCart Popup Lite: 1.1
> Wordfence Security: 6.2.10
> WPBruiser: 3.1.3
> WP Maintenance Mode: 2.0.9
> WP Smush: 2.5.3
> YITH WooCommerce Anti-Fraud: 1.0.6
> YITH WooCommerce Compare: 2.1.0
> YITH WooCommerce Quick View: 1.1.4
> YITH WooCommerce Review Reminder: 1.2.1
> YITH WooCommerce Waiting List: 1.0.8
> YITH WooCommerce Watermark: 1.0.11
> YITH WooCommerce Wishlist: 2.0.16
> 
> PHP Version: 5.5.38
> MySQL Version: 5.1.73
> Web Server Info: Apache
> 
> WordPress Memory Limit: 256MB
> PHP Memory Limit: 256M
> PHP Upload Max Size: 16M
> PHP Post Max Size: 16M
> PHP Upload Max Filesize: 16M
> PHP Time Limit: 150
> PHP Max Input Vars: 1000
> PHP Arg Separator: &
> PHP Allow URL File Open: Yes
> WP_DEBUG: Disabled
> 
> Show On Front: page
> Page On Front: Montra | Novidades, Promoções e Destaques (#306)
> Page For Posts: Artigos (#1446)

**Comment by eri-trabiccolo** [comment]
So as suspected the problem is Download Manager ('cause it embeds bootstrap3, though it has options to not enqueue b3 resources).

Let me see if the b3 fix solves this too.
