### ISSUE TITLE
Ultimate Membership Pro : problem when uploading an avatar with the Customizr theme

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#747]
User email below.

> Hey!
> 
> On my website, idodrums.com, I'm using the free version of your theme Customizr, I've had a few problems with a good number of themes (which becomes pretty expensive) in the past so thank you for offering a free trial!
> 
> I've recently put on a plugin called Ultimate Membership Pro and got in touch with them when I found I wasn't able to upload an avatar as a user, they asked me to try out one of the Wordpress original themes and the Upload button started to work, the UMP support guys said it could be to do with the theme's js scripts.
> 
> 
> Hope you can help, look forward to hearing back.
> 
> Chris

**Comment by Nikeo** [comment]
( Ultimate Membership Pro has been sent to you by email )

**Comment by eri-trabiccolo** [comment]
smartlaod related, almost done with a fix.
Of course impacts hueman too.

**Comment by eri-trabiccolo** [comment]
I tested it locally with the Ultimate Membership Pro plugin.
I also tested it on our testing website without the aforementioned plugin but with jetpak's photon.

Do you want a PR for hueman or will you fix it manually there?

**Comment by eri-trabiccolo** [comment]
same PR done for Hueman ;)

**Comment by nimrashafibutt1** [comment]
Hi , I'm having the same issue can you please share this with me as well ?
