### ISSUE TITLE
Problems with Slider in Customizr V 3.4.38

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#752]
https://wordpress.org/support/topic/problems-with-slider-in-customizr-v-3-4-38/

> Hello, I just updated to the version and the text and arrows of the slider have moved down with respect to the image … I already tried disabling each of the plugins I installed, but that does not fix the problem. I’m using a child-theme, but the only thing modified there are the following lines (which have nothing to do with the slider):
> 
> /* DISABLE SEMI-TRANSPARENCY FOR STICKY HEADER ON SCROLL*/
> .tc-solid-color-on-scroll.sticky-enabled .tc-header,
> .tc-solid-color-on-scroll.sticky-enabled .navbar-inner {
>   background-color: #FFFFFF;
> }
> 
> /*TAMAÑO MINIMO DEL LOGO CON EL SHRINK ACTIVADO*/
> .sticky-enabled .tc-shrink-on .site-logo img {
>     height: 70px !important;
>     width: auto !important;
> }
> I include a screenshot. Thank you.

**Comment by Nikeo** [comment]
also reported here :  https://secure.helpscout.net/conversation/308707895/22071/?folderId=607544

**Comment by eri-trabiccolo** [comment]
So server side caching issues mostly.

**Comment by Nikeo** [comment]
OK thanks
