### ISSUE TITLE
An optional simple search icon in the header

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#780]
no fancy effect, just like in the Hueman theme.
The difference with Hueman would be that it would have to be inside the hamburger menu when enabled ( either on desktop or mobiles )
If the regular menu is displayed, it would have to be placed like the WooCommerce cart.

@eri-trabiccolo what do you think ? Complexity ?
No emergency

**Comment by eri-trabiccolo** [comment]
the problem is that the Customizr header is very crowded right now.
E.g. to allow the WooCommerce icon cart we filter the tagline class to narrow it...
Maybe we might need a topnav ...
