### ISSUE TITLE
Prevdem contents when theme directory is not customizr

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#785]
https://wordpress.org/support/topic/front-page-has-changed-2/

**Comment by Nikeo** [comment]
Ok thanks for reporting.
Can you fix it. A possibility would be to act on the is_prevdem() boolean to handle this case

**Comment by eri-trabiccolo** [comment]
Not an issue itself, the user just used a temporary directory.

**Comment by eri-trabiccolo** [comment]
(was already replying when you posted your reply)
ok I'll look at it

**Comment by eri-trabiccolo** [comment]
fixed in #827
