### ISSUE TITLE
Disable loading jquery fancybox from customizr

### ISSUE THREAD

**Issue by martinkiteur** [presscustomizr/customizr#788]
Hello,

Is that possible to disable loading jquery fancybox from customizr ?

I have a problem loading a plugin using fancybox on this page https://tst.evo-spirit.com/commande/
A product to test adding to cart https://www.evo-spirit.com/produit/chargeur-pour-batterie-sla-24v-16a-prise-xlr/

When you choose shipping via RelayColis th fancy popup doesn't load.
May be you know why ?

Best regards.

**Comment by eri-trabiccolo** [comment]
Hello,
yeah that's possible.
Take a look at this doc:
http://docs.presscustomizr.com/article/149-a-button-stopped-working-on-my-website

Does it help?

**Comment by martinkiteur** [comment]
Hello,

That's it, thanks !
Have to disable 2 features to avoid the loading of Customizr scripts fancybox.

Best regards.

**Comment by eri-trabiccolo** [comment]
Yeah, because it's needed for both of them.
The theme offers a way to avoid conflicts and/or not load the resource when not needed.

Glad you solved.
Best regards,
Rocco
