### ISSUE TITLE
Shortcodes Ultimate : Slider shortcode does not display correctly

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#803]
As reported by a user 
> When using the slider shortcode in a page and Previewing changes then the slider displays correctly.
> 
> Yet viewing the page via menu's then the slider does not display.
> 
> Example: [su_slider source="media: 364,365,366,367" width="500" height="340" responsive="no" title="no" centered="no" arrows="no" pages="no" mousewheel="no"]
> 
> 
> I'm using a child theme of Customizr v3.5.1 with WP version 4.7.2.
> 
> Shortcodes Ultimate version 4.9.9

**Comment by Nikeo** [comment]
@eri-trabiccolo it might be worth testing this free plugin when you have time. It's been a while now since I did not use it. Except than chekcing the compatibility, I do think that this plugin could be inspiring for the modularity it's bringing. I have the sektions in mind of course.
https://fr.wordpress.org/plugins/shortcodes-ultimate/

**Comment by eri-trabiccolo** [comment]
@Nikeo 
smartload issue

**Comment by eri-trabiccolo** [comment]
[Forgot to publish this comment]
I have no way at the moment to fix this.
The js they use seems to remove (but keeping the style, display: none produced by the hide) the img node from the dom after we hide it and replace the attributes here:
https://github.com/presscustomizr/front-jquery-plugins/blob/master/jqueryimgSmartLoad.js#L131

but before we process the "load":
https://github.com/presscustomizr/front-jquery-plugins/blob/master/jqueryimgSmartLoad.js#L142

So as of now, no compatibility with our smartload.
Unless we decide to remove the "hide" which means losing the fade-in.
Force the displaying with CSS as workaround?!
