### ISSUE TITLE
Caret submenu icons should be consistently displayed accross mobile / desktop menu design options

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#804]
https://wordpress.org/support/topic/after-the-update-an-icon-in-the-mobile-menu-is-missed/#post-8786061

> I cannot understand.
> IS ok that in mobile there are NOT dropdown. The issue is that if I set the menu to show sub pages only on mouse click than mobile menu is showed correctly with the drop down menu and all sub page visible this is ok.
> 
> If I select to show (on Desktop) the sub pages on mouse over the mobile menu is the same as before but is missed the drop down icon.
> 
> This seems to be a bug not something that is not supported. Ok that on mobile you cannot have drop down but mobile menu should have near mean page with sub pages this symbol:
> https://s5.postimg.org/h9fi9fq47/screen_missed_simbol_main_page.pngscreen and if I set that in Desktop I want sub page are showed on mouse over the mobile menu is missed the drop down icon.

**Comment by eri-trabiccolo** [comment]
Mah

**Comment by PeopleInside** [comment]
Yes I saw that if you set the header settings to show sub pages only on mouse click than mobile menu are showed well with the Caret sub menu and this looks nice BUT if you had chosen to show sub page on mouse over the mobile menu is missing the caret sub menu icon. With that icon mobile menu are more easy to understand so I suggest as in the title of this topic to add it also when the option of show sub pages are set to "on mouse overlap".

If this will be not fixed I will be happy to have a solution for enable it on my case (enable the sub caret icon)

Thank you.

**Comment by eri-trabiccolo** [comment]
Hi PeopleInside,
thanks for your exhaustive explanation.
Much appreciated.
We'll look into that ;)
