### ISSUE TITLE
The Event Calendar : Data Formatting issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#814]
> I am using a plugin called Event Calendar which is recommended by you on your web site documentation.
> 
> 
> Within this plugin there is an issue relating to formatting address data which according to the plugin developer is an issue with my theme.
> 
> To see an example of this problem please take a look at the following event within the Plugin calendar.
> 
> http://glandorevillage.ie/event/coffee-morning/
> 
> Please note the field that contains the address portion, just before the link to +Google Map
> 
> 
> You will note the words GlandoreCorkIreland.
> 
> These three words should be separated by spaces, but they are not. how do i fix this please?
> 
> 
> thanks

**Comment by eri-trabiccolo** [comment]
Cannot see any rule of our CSS which overrides the plugin's ones.

**Comment by eri-trabiccolo** [comment]
So the problem there is this:
Elements are displayed inline, the space between them, relies on the fact that between the elements tag there are actual spaces. Like
`<span>el1</span> <span>el2</span>`
Most likely the html code of that portion is originally printed in the aforementioned way.
Though, in the website above, the html is "compacted" with some plugin. This compacting process removes those spaces.
So:
1) not a theme issue
2) the plugin which creates that html has to take care of its elements rendering

I close this.
