### ISSUE TITLE
Recently updated notice not showing up on home page post grid ( Customizr Pro )

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#816]
Hi,

Reported by user on helpscout
https://secure.helpscout.net/conversation/323445436/23791/?folderId=607541

I am able to replicate this issue.

In Customizr Pro.
Go to Appearance -> Customize -> Content -> Post metas
Enable -> Display a recent update notice

Edit a post and save changes.
The word "Recently updated !" does not display on homepage post grid.

I had tried enabling and disabling -> Display posts metas on home
But it makes no differences.

Thank you

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Hi Denzel,
thanks for reporting this.

Actually the theme doesn't display the update notice by default (since ages) in the pro grid.

We can probably allow this when the title is displayed below the post.

I close this here and move it in the pro github repository ;)

**Comment by Nikeo** [comment]
@denzelchia thx for reporting
@eri-trabiccolo I don't want the recently updated notice in the pro grid, even when title is displayed below the post.

**Comment by denzelchia** [comment]
Hi,

The recently updated notice is in Customizr theme.
This is why user expected it to show up in Customizr Pro theme.

User expects to retain free feature and have Pro features. Not to lose any free feature that they are using daily after paying for Pro theme.

If that feature is redundant, it should also be removed in free version.

These are some of my opinions for consideration.

Thank you.

**Comment by Nikeo** [comment]
And this makes totally sense I agree. It's just that I don't like this notice from a design stand point ...
OK I will think about this a little more.
Cheers
