### ISSUE TITLE
error in czr-front.php

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#830]
> I am getting the error ” Invalid arguments passed in /var/www/html/wp-content/themes/customizr/inc/czr-front.php on line 4055″
> 
> I am not able to figure out what exactly is causing the error as I am not a technical person. Please let me know how to fix it and how to figure out what is causing the problem.

https://wordpress.org/support/topic/error-in-czr-front-php/

**Comment by Nikeo** [comment]
@eri-trabiccolo would you mind having a look when you can ?
Thanks

**Comment by eri-trabiccolo** [comment]
https://github.com/presscustomizr/customizr/blob/master/inc/czr-front.php#L4055
If not for a custom code, there might a case when the header_class is not an array.
https://github.com/presscustomizr/customizr/blob/master/inc/czr-front.php#L4236

PR on the way.

**Comment by Nikeo** [comment]
thanks

**Comment by eri-trabiccolo** [comment]
Honestly that part is a bit messy :/ 
Fixex
