### ISSUE TITLE
Italian translation error on 404 page

### ISSUE THREAD

**Issue by PeopleInside** [presscustomizr/customizr#842]
![1](https://cloud.githubusercontent.com/assets/5006150/23830138/956f81c2-0703-11e7-9829-4b88834bb867.png)

This is the screen from 404 page.
The last question "Vuoi provare a cercarlo?" should be "Vuoi provare a cercarla?"

**Comment by eri-trabiccolo** [comment]
Thank you very much!
I approved your translation on 
https://translate.wordpress.org/locale/it/default/wp-themes/customizr

In this repository the localization files under lang-pro are intended for the theme's pro version.
They're retrieved from translate.wordpress.org when building the pro-version (and loaded for pro users who don't also have the free version installed).

Your approved translation will be then available as soon as the WP routine will generate the new italian lang-pack for the theme (generally in a couple of hours). 

Thanks
