### ISSUE TITLE
jetpack minor conflict : facebook widget

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#847]
> 1st topic - in the widget "facebook page" (from jetpack), the title have a font color different of all others widgets
> 
> https://drive.google.com/file/d/0B_m
![customizr bug 1](https://cloud.githubusercontent.com/assets/3038156/23846880/ebef5c3a-07cf-11e7-897d-b5d02c4c44c7.JPG)
ag9dm0wI9UGl1Zm84N19LbEE/view?usp=sharing
> 
> 
> thanks in advance,
> 
> luciano

**Comment by eri-trabiccolo** [comment]
Because it's a link ?!

**Comment by Nikeo** [comment]
yes probably.
