### ISSUE TITLE
When logo is centered, we should be able to center the horizontal menu

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#861]
## Scope
this applies to
- the horizontal menu
- on devices where it is not turned into hamburger of course ( => tablet portrait )

## Customizer
- a new select option "Menu centered" should be added to `tc_second_menu_position`
- a js dependency should be triggered when `tc_header_layout` is set to `centered` => tc_second_menu_position value automatically set to the newly created select option.

**Comment by eri-trabiccolo** [comment]
Questions:
## Scope
would this apply
- when sticky enabled and scrolling (.sticky-enabled)?
  _Depending on which elements are visible and which solution we adopt to center it it might:_
    a) not be centered in the whole header but centered in its own container
    b) centered in the header but dropping on a new line

- never when sticky enabled and scrolling (.sticky-enabled)?
_We have to inform it doesn't and deal with same kind of requests to make it apply when scrolling_

  - where to place the menu? Left or right? 
_This is an information we'll lose if we add this option as an alternative to "left" or "right"._

- secondary menu (which is horizontal too)?

**Comment by Nikeo** [comment]
yes it applies to any horizontal menu inside the header
not centered when sticky

**Comment by eri-trabiccolo** [comment]
take a look at this draft:
https://github.com/presscustomizr/customizr/pull/862

Do you like the "disabling" thing or do you prefer to remove it?
Let me know
