### ISSUE TITLE
hentry structured data

### ISSUE THREAD

**Issue by twinsdz** [presscustomizr/customizr#864]
Hi

The **autor** and **update** properties for the hentry structured data is missing. It will be nice if you add it. 

Hier you can see more about my question https://wordpress.org/support/topic/fix-google-rich-snippets-errors/#post-8959048. 

Best regards

**Comment by eemlandict** [comment]
She is right.. It`s a missing thing in thema what cause this error
what google don`t like for your ranking

![hentry](https://user-images.githubusercontent.com/17732874/34958762-8aa5e4b0-fa33-11e7-961e-dc496d82c1d2.jpg)

see also
https://kb.yoast.com/kb/fixing-hcard-author-error/
The solution is in template
https://wpcolt.com/fix-hentry-errors-wordpress/

**Comment by joshin16** [comment]
Hello, I had gone through above reference links to resolve the same issue on my website https://www.games.meramaal.com but unable to fix it ..its not clear please help me

**Comment by eemlandict** [comment]
Is there a reason.. why you won`t fix it?

**Comment by ghost** [comment]
typo it's been fixed : https://github.com/eri-trabiccolo/customizr/commit/9f4bdba9aa3f2d27450ffdf66a27c89ca4f99176
