### ISSUE TITLE
WooCommerce admin javascript error ( Customizr Pro Theme )

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#871]
Hi,

This issue is reported by customer on helpscout.
https://secure.helpscout.net/conversation/345010016/25533/?folderId=607541#thread-928281680

Customizr Pro Theme 1.3.4 and WooCommerce 3.0.0
In WooCommerce, Add New Product interface, the Product data tabs are not working.
There is javascript error.

<img width="1670" alt="screen shot 2017-04-06 at 10 19 57 am" src="https://cloud.githubusercontent.com/assets/9284811/24735238/857ab2ea-1ab4-11e7-9693-fa56779c8fba.png">

Works properly in Customizr ( Free ) Theme.

Thank you

**Comment by Nikeo** [comment]
Thanks for reporting the problem @denzelchia

**Comment by eri-trabiccolo** [comment]
Moved into the relevant repo:
https://github.com/presscustomizr/pro-bundle/issues/55
