### ISSUE TITLE
Add Support for WooCommerce Gallery

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#872]
Hi,

With reference to the following forum thread.
https://wordpress.org/support/topic/product-photo-gallery-2/

WooCommerce removed the product gallery feature and need themes to use add_theme_support
https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/

Please consider adding back support for this feature.

Thank you

**Comment by Nikeo** [comment]
Thanks for reporting the problem too @denzelchia
